CREATE TABLE operacionlavado (
	operacionid serial NOT NULL,
	autorizado INTEGER NULL DEFAULT NULL,
	tiporeporte TEXT NULL DEFAULT NULL,
	periodoreporte TEXT NULL DEFAULT NULL,
	folio TEXT NULL DEFAULT NULL,
	organismosupervisor TEXT NULL DEFAULT NULL,
	claveentidad TEXT NULL DEFAULT NULL,
	localidad TEXT NULL DEFAULT NULL,
	sucursal TEXT NULL DEFAULT NULL,
	tipooperacion TEXT NULL DEFAULT NULL,
	intrumentomonetario TEXT NULL DEFAULT NULL,
	numerocuenta TEXT NULL DEFAULT NULL,
	monto TEXT NULL DEFAULT NULL,
	moneda TEXT NULL DEFAULT NULL,
	fechaoperacion TEXT NULL DEFAULT NULL,
	fechadetencion TEXT NULL DEFAULT NULL,
	nacionalidad TEXT NULL DEFAULT NULL,
	tipopersona TEXT NULL DEFAULT NULL,
	razonsocial TEXT NULL DEFAULT NULL,
	nombre TEXT NULL DEFAULT NULL,
	paterno TEXT NULL DEFAULT NULL,
	materno TEXT NULL DEFAULT NULL,
	rfc TEXT NULL DEFAULT NULL,
	curp TEXT NULL DEFAULT NULL,
	fechanacimiento TEXT NULL DEFAULT NULL,
	domicilio TEXT NULL DEFAULT NULL,
	colonia TEXT NULL DEFAULT NULL,
	ciudad TEXT NULL DEFAULT NULL,
	telefono TEXT NULL DEFAULT NULL,
	actividadeconomica TEXT NULL DEFAULT NULL,
	nombreagente TEXT NULL DEFAULT NULL,
	paternoagente TEXT NULL DEFAULT NULL,
	maternoagente TEXT NULL DEFAULT NULL,
	rfcagente TEXT NULL DEFAULT NULL,
	curpagente TEXT NULL DEFAULT NULL,
	consecutivocuentas TEXT NULL DEFAULT NULL,
	numcuenta TEXT NULL DEFAULT NULL,
	claveentidadfinanciera TEXT NULL DEFAULT NULL,
	nombrecuentarelacionada TEXT NULL DEFAULT NULL,
	paternocuentarelacionada TEXT NULL DEFAULT NULL,
	maternocuentarelacionada TEXT NULL DEFAULT NULL,
	descripcion TEXT NULL DEFAULT NULL,
	razon TEXT NULL DEFAULT NULL,
	ejercicio INTEGER NULL DEFAULT NULL,
	periodo INTEGER NULL DEFAULT NULL,
	tipointerno integer,
	PRIMARY KEY (operacionesrelevantesid)
)
;