\i mod_finalidades.sql
\i mod_prestamos.sql
\i mod_amortizaciones.sql
\i cat_cuentas_tipoprestamo.sql
\i migra_cuentas_tipoprestamo.sql

\i calculadiasmora.sql
\i cancelapoliza.sql
\i carteracrediticiaccomite.sql
\i carteracrediticiasioef.sql
\i castigoprestamo.sql
\i corrige_tablas_amortizaciones.sql
\i cortecajadepbancario.sql
\i cortecajaefectivo.sql
\i cortecajatransfer.sql
\i devengainteres.sql
\i dias_mora_linea.sql
\i diasmorainteres.sql
\i fechaprimeradeudo.sql
\i fechaultimapagada.sql
\i fsaldocalculado.sql
\i interesdevmoratorio.sql
\i movimientoscaja.sql
\i movprestamo.sql
\i movslinead.sql
\i num_disposicion_linea.sql
\i precierre.sql
\i reporte_lineas_credito.sql
\i reporteburo.sql
\i saldocalculado.sql
\i saldomov.sql
\i sprecuperacion.sql
\i spscalculopago.sql
\i spscontarpagossocio.sql
\i spsprestamos.sql
\i spssaldoadeudolinea.sql
\i spssaldoadeudolineafecha.sql
\i spssaldodisplinea.sql
\i spssumapagos.sql
\i spssumapagosgrupal.sql
\i spssumapagossocio.sql
\i ultimoabonointeres.sql
\i verificaamortizacionpagada.sql
\i verificainterespagado.sql