\i cajerosuc.sql
\i cortecajaefectivo.sql
\i cortecajatransfer.sql
\i cortedepbancario.sql
\i cuentasdesbloqueadas.sql
\i mayoresmenoressioef.sql
\i movimientoscaja.sql
\i spchsalcobro.sql
\i spsinversionpagada.sql
\i spsinversionporcaja.sql
\i spsmovimientos.sql
\i spsmovimientosmayor.sql
\i spsmovimientosmenor.sql
\i tablaapoyosocial.sql
\i tablacambiocheques.sql
\i tablachequesalvobuenbobro.sql
\i tablamovremesas.sql
\i tablasocioidtipomov.sql
\i tipomovcaja.sql
\i spimovicaja_Ver009.sql
\i spisabana.sql
\i inserta_cajeros.sql
\i inserta_extensiontipomovimieto.sql
\i spscajerosucid.sql