--DROP TABLE cat_cuentas_tipoprestamo;
CREATE TABLE cat_cuentas_tipoprestamo(
  cat_cuentasid serial NOT NULL,
  tipoprestamoid varchar(3) NOT NULL references tipoprestamo(tipoprestamoid),
  clavefinalidad char(3) NOT NULL references cat_finalidad_contable(clavefinalidad),
  renovado int4,
  cuentaactivo varchar(24) references catalogo_ctas(cuentaid),
  cuentaactivovencida varchar(24) references catalogo_ctas(cuentaid),
  cuentaintnormal varchar(24) references catalogo_ctas(cuentaid),
  cuentaintnormalvencida varchar(24) references catalogo_ctas(cuentaid),
  cuentaintnormalnocob varchar(24) references catalogo_ctas(cuentaid),
  cuentaintmora varchar(24) references catalogo_ctas(cuentaid),
  cuentaintmoravencida varchar(24) references catalogo_ctas(cuentaid),
  cuentaiva varchar(24) references catalogo_ctas(cuentaid),
  cuentariesgocred varchar(24) references catalogo_ctas(cuentaid),
  cuentaordeninteres varchar(24) references catalogo_ctas(cuentaid),
  cuentaintdevnocobres varchar(24) references catalogo_ctas(cuentaid),
  cuentariesgocredres varchar(24) references catalogo_ctas(cuentaid),
  cuentaintmoranocobact varchar(24) references catalogo_ctas(cuentaid),
  cuentaintmoradevnocobres varchar(24) references catalogo_ctas(cuentaid),
  ordendeudornormalbonificado varchar(24) references catalogo_ctas(cuentaid),
  ordenacredornormalbonificado varchar(24) references catalogo_ctas(cuentaid),
  cuentaintnormalresvencida varchar(24) references catalogo_ctas(cuentaid),
  ordeninteresacreedor varchar(24) references catalogo_ctas(cuentaid),
  cuentaintnormalresvigente varchar(24) references catalogo_ctas(cuentaid),
  cuentacomision varchar(24) references catalogo_ctas(cuentaid),
  cuentaivacomision varchar(24) references catalogo_ctas(cuentaid), 
  clasificacioncontable varchar(24),
  moravigentebalance varchar(24) references catalogo_ctas(cuentaid),
  moravencidobalance varchar(24) references catalogo_ctas(cuentaid),
  moravigenteresultado varchar(24) references catalogo_ctas(cuentaid),
  moravencidoresultado varchar(24) references catalogo_ctas(cuentaid),
  moractaordendeudora varchar(24) references catalogo_ctas(cuentaid),
  moractaordenacredora varchar(24) references catalogo_ctas(cuentaid),
  PRIMARY KEY (cat_cuentasid),
  UNIQUE (tipoprestamoid,clavefinalidad,renovado)
);

