--DROP TABLE cat_cuentas_tipoprestamo;
CREATE TABLE cat_cuentas_tipoprestamo(
  cat_cuentasid serial NOT NULL,
  tipoprestamoid char(3) NOT NULL references tipoprestamo(tipoprestamoid),
  clavefinalidad char(3) NOT NULL references cat_finalidad_contable(clavefinalidad),
  renovado int4 not null,
  cuentaactivo char(24) references catalogo_ctas(cuentaid),
  cuentaactivovencida char(24) references catalogo_ctas(cuentaid),
  cuentaintnormal char(24) references catalogo_ctas(cuentaid),
  cuentaintnormalvencida char(24) references catalogo_ctas(cuentaid),
  cuentaintnormalnocob char(24) references catalogo_ctas(cuentaid),
  cuentaintmora char(24) references catalogo_ctas(cuentaid),
  cuentaintmoravencida char(24) references catalogo_ctas(cuentaid),
  cuentaiva char(24) references catalogo_ctas(cuentaid),
  cuentariesgocred char(24) references catalogo_ctas(cuentaid),
  cuentaordeninteres char(24) references catalogo_ctas(cuentaid),
  cuentaintdevnocobres char(24) references catalogo_ctas(cuentaid),
  cuentariesgocredres char(24) references catalogo_ctas(cuentaid),
  cuentaintmoranocobact char(24) references catalogo_ctas(cuentaid),
  cuentaintmoradevnocobres char(24) references catalogo_ctas(cuentaid),
  ordendeudornormalbonificado char(24) references catalogo_ctas(cuentaid),
  ordenacredornormalbonificado char(24) references catalogo_ctas(cuentaid),
  cuentaintnormalresvencida char(24) references catalogo_ctas(cuentaid),
  ordeninteresacreedor char(24) references catalogo_ctas(cuentaid),
  cuentaintnormalresvigente char(24) references catalogo_ctas(cuentaid),
  cuentacomision char(24) references catalogo_ctas(cuentaid),
  cuentaivacomision char(24) references catalogo_ctas(cuentaid), 
  clasificacioncontable char(24),
  moravigentebalance char(24) references catalogo_ctas(cuentaid),
  moravencidobalance char(24) references catalogo_ctas(cuentaid),
  moravigenteresultado char(24) references catalogo_ctas(cuentaid),
  moravencidoresultado char(24) references catalogo_ctas(cuentaid),
  moractaordendeudora char(24) references catalogo_ctas(cuentaid),
  moractaordenacredora char(24) references catalogo_ctas(cuentaid),
  PRIMARY KEY (cat_cuentasid),
  UNIQUE (tipoprestamoid,clavefinalidad,renovado)
);

