insert into ocupacion_actividad_finafim values ('MAESTRO',611,'SERVICIOS EDUCATIVOS');
insert into ocupacion_actividad_finafim values ('DOCTOR',621,'SERVICIOS MEDICOS DE CONSULTA EXTERNA Y SERVICIOS RELACIONADOS');
insert into ocupacion_actividad_finafim values ('ENFEREMRA',621,'SERVICIOS MEDICOS DE CONSULTA EXTERNA Y SERVICIOS RELACIONADOS');
insert into ocupacion_actividad_finafim values ('COMERCIANTE',461,'COMERCIO AL POR MENOR DE ALIMENTOS, BEBIDAS Y TABACO');
insert into ocupacion_actividad_finafim values ('GERENTE',561,'SERVICIOS DE APOYO A LOS NEGOCIOS');
insert into ocupacion_actividad_finafim values ('CONTADOR',561,'SERVICIOS DE APOYO A LOS NEGOCIOS');
insert into ocupacion_actividad_finafim values ('AGRICULTURA',111,'AGRICULTURA');
insert into ocupacion_actividad_finafim values ('CAMPESINO',111,'AGRICULTURA');
insert into ocupacion_actividad_finafim values ('GANADERO',112,'GANADERIA');
insert into ocupacion_actividad_finafim values ('SILVICOLA Y FORESTAL',321,'INDUSTRIA DE LA MADERA');
insert into ocupacion_actividad_finafim values ('ENVASADO ALIMENTOS/BEBIDAS',311,'INDUSTRIA ALIMENTARIA');
insert into ocupacion_actividad_finafim values ('TEXTILES Y SIMILARES',314,'CONFECCION DE PRODUCTOS TEXTILES, EXCEPTO PRENDAS DE VESTIR');
insert into ocupacion_actividad_finafim values ('INDUSTRIA DEL VESTIDO',315,'FABRICACION DE PRENDAS DE VESTIR');
insert into ocupacion_actividad_finafim values ('CONSTRUCCION',236,'EDIFICACION');
insert into ocupacion_actividad_finafim values ('MATERIALES P/CONSTRUCCION',467,'COMERCIO AL POR MENOR DE ARTICULOS DE FERRETERIA, TLAPALERIA Y VIDRIOS');
insert into ocupacion_actividad_finafim values ('HOTEL',721,'SERVICIOS DE ALOJAMIENTO TEMPORAL');
insert into ocupacion_actividad_finafim values ('TRANSPORTE (CHOFER)',485,'TRANSPORTE TERRESTRE DE PASAJEROS, EXCEPTO POR FERROCARRIL');
insert into ocupacion_actividad_finafim values ('RESTAURANTE / COMEDOR',722,'SERVICIOS DE PREPARACION DE ALIMENTOS Y BEBIDAS');
insert into ocupacion_actividad_finafim values ('TELECOMUNICACIONES',469,'INTERMEDIACION Y COMERCIO AL POR MENOR POR MEDIOS MASIVOS DE COMUNICACION Y OTROS MEDIOS');
insert into ocupacion_actividad_finafim values ('SERVICIOS EDUCATIVOS',611,'SERVICIOS EDUCATIVOS');
insert into ocupacion_actividad_finafim values ('CONSULTORIA Y ASESORIA',561,'SERVICIOS DE APOYO A LOS NEGOCIOS');
insert into ocupacion_actividad_finafim values ('ARQUITECTO',236,'EDIFICACION');
insert into ocupacion_actividad_finafim values ('ABOGADO',812,'SERVICIOS PERSONALES');
insert into ocupacion_actividad_finafim values ('MESERO (A)',722,'SERVICIOS DE PREPARACION DE ALIMENTOS Y BEBIDAS');
insert into ocupacion_actividad_finafim values ('COMERCIANTE AMBULANTE',463,'COMERCIO AL POR MENOR DE PRODUCTOS TEXTILES, ACCESORIOS DE VESTIR Y CALZADO');
insert into ocupacion_actividad_finafim values ('FARMACIAS Y SIMILARES',464,'COMERCIO AL POR MENOR DE ARTICULOS PARA EL CUIDADO DE LA SALUD');
insert into ocupacion_actividad_finafim values ('NEGOCIO PROPIO',462,'COMERCIO AL POR MENOR EN TIENDAS DE AUTOSERVICIO Y DEPARTAMENTALES');
insert into ocupacion_actividad_finafim values ('FOTOGRATO / FOTOESTUDIO',8129,'SERVICIOS DE REVELADO DE FOTOGRAFIAS Y OTROS SERVICIOS PERSONALES');
insert into ocupacion_actividad_finafim values ('PLOMERO / ELECTRICISTA',5612,'SERVICIOS COMBINADOS DE APOYO EN INSTALACIONES');
insert into ocupacion_actividad_finafim values ('CARPINTERO',337,'FABRICACION DE MUEBLES Y PRODUCTOS RELACIONADOS');
insert into ocupacion_actividad_finafim values ('VENTA FRUTAS Y LEGUMBRES',461,'COMERCIO AL POR MENOR DE ALIMENTOS, BEBIDAS Y TABACO');
insert into ocupacion_actividad_finafim values ('TABLAJERO  (carnicero)',461,'COMERCIO AL POR MENOR DE ALIMENTOS, BEBIDAS Y TABACO');
insert into ocupacion_actividad_finafim values ('ENVASADO FRUTAS/LEGUMBRES',311,'INDUSTRIA ALIMENTARIA');
insert into ocupacion_actividad_finafim values ('CATEDRATICO',611,'SERVICIOS EDUCATIVOS');
insert into ocupacion_actividad_finafim values ('SERV. EDUCACION PARTICULAR',611,'SERVICIOS EDUCATIVOS');
insert into ocupacion_actividad_finafim values ('INGENIERO',238,'TRABAJOS ESPECIALIZADOS PARA LA CONSTRUCCION');
insert into ocupacion_actividad_finafim values ('CIRUJANO DENTISTA',621,'SERVICIOS MEDICOS DE CONSULTA EXTERNA Y SERVICIOS RELACIONADOS');
insert into ocupacion_actividad_finafim values ('VENTAS / DISTRIBUCION',488,'SERVICIOS RELACIONADOS CON EL TRANSPORTE');
insert into ocupacion_actividad_finafim values ('HERRERO / BALCONERO',5612,'SERVICIOS COMBINADOS DE APOYO EN INSTALACIONES');
insert into ocupacion_actividad_finafim values ('SERVICIOS DE SALUD',621,'SERVICIOS MEDICOS DE CONSULTA EXTERNA Y SERVICIOS RELACIONADOS');
insert into ocupacion_actividad_finafim values ('ARTESANO',314,'CONFECCION DE PRODUCTOS TEXTILES, EXCEPTO PRENDAS DE VESTIR');
insert into ocupacion_actividad_finafim values ('ENFERMERA',621,'SERVICIOS MEDICOS DE CONSULTA EXTERNA Y SERVICIOS RELACIONADOS');
insert into ocupacion_actividad_finafim values ('HOTELERO',721,'SERVICIOS DE ALOJAMIENTO TEMPORAL');

insert into ocupacion_actividad_finafim values ('ALBAÑIL',236,'EDIFICACION');
insert into ocupacion_actividad_finafim values ('AYUDANTE DE ALBAÑIL',236,'EDIFICACION');
insert into ocupacion_actividad_finafim values ('ESTILISTA',8121,'SALONES Y CLINICAS DE BELLEZA, BAÑOS PUBLICOS Y BOLERIAS');
insert into ocupacion_actividad_finafim values ('MÚSICO',711,'SERVICIOS ARTISTICOS Y DEPORTIVOS Y OTROS SERVICIOS RELACIONADOS');
insert into ocupacion_actividad_finafim values ('MECÁNICO',811,'SERVICIOS DE REPARACION Y MANTENIMIENTO');