insert into preguntasmatrizriesgo (preguntaid,descripcion) values (1,'Que tipo de operaciones realiza en la cooperativa');
insert into preguntasmatrizriesgo (preguntaid,descripcion) values (2,'Zona geografica. Lugar de Nacimiento');
insert into preguntasmatrizriesgo (preguntaid,descripcion) values (3,'Nacionalidad');
insert into preguntasmatrizriesgo (preguntaid,descripcion) values (4,'Edad');
insert into preguntasmatrizriesgo (preguntaid,descripcion) values (5,'Estado civil');
insert into preguntasmatrizriesgo (preguntaid,descripcion) values (6,'Tiempo laborando en su actual empleo');
insert into preguntasmatrizriesgo (preguntaid,descripcion) values (7,'Monto aproximado mensual de las operaciones');
insert into preguntasmatrizriesgo (preguntaid,descripcion) values (8,'Actividad general');
insert into preguntasmatrizriesgo (preguntaid,descripcion) values (9,'Instrumento monetario');
insert into preguntasmatrizriesgo (preguntaid,descripcion) values (10,'Frecuencia de operaciones');
insert into preguntasmatrizriesgo (preguntaid,descripcion) values (11,'Propiedad de los recursos');
insert into preguntasmatrizriesgo (preguntaid,descripcion) values (12,'Tipo de residencia');
insert into preguntasmatrizriesgo (preguntaid,descripcion) values (13,'Ingreso del Conyuge');
insert into preguntasmatrizriesgo (preguntaid,descripcion) values (14,'Tiene algun puesto politico');
insert into preguntasmatrizriesgo (preguntaid,descripcion) values (15,'Algun familiar de usted, hasta segundo grado, ocupa algun puesto politico');
insert into preguntasmatrizriesgo (preguntaid,descripcion) values (16,'Tipo de personalidad juridica');
insert into preguntasmatrizriesgo (preguntaid,descripcion) values (17,'Tiempo de residencia en el estado');
insert into preguntasmatrizriesgo (preguntaid,descripcion) values (18,'Antiguedad domiciliaria');
insert into preguntasmatrizriesgo (preguntaid,descripcion) values (19,'Se encuentra en la lista de la OFAC');
insert into preguntasmatrizriesgo (preguntaid,descripcion) values (20,'Total de ingresos');