drop table actividadbanxico;
CREATE TABLE actividadbanxico
(
  actividadid character varying(10),
  nombre character varying(60),
  PRIMARY KEY (actividadid)
  )
WITH (
  OIDS=FALSE
);
insert into actividadbanxico values('0111013','CULTIVO DE ALPISTE');
insert into actividadbanxico values('0111021','CULTIVO DE ARROZ');
insert into actividadbanxico values('0111039','CULTIVO DE AVENA');
insert into actividadbanxico values('0111047','CULTIVO DE CEBADA');
insert into actividadbanxico values('0111055','CULTIVO DE LINAZA');
insert into actividadbanxico values('0111063','CULTIVO DE MAIZ');
insert into actividadbanxico values('0111071','CULTIVO DE MILO');
insert into actividadbanxico values('0111089','CULTIVO DE SORGO');
insert into actividadbanxico values('0111097','CULTIVO DE SOYA');
insert into actividadbanxico values('0111104','CULTIVO DE TRIGO');
insert into actividadbanxico values('0112011','CULTIVO DE AJO');
insert into actividadbanxico values('0112029','CULTIVO DE CALABAZA');
insert into actividadbanxico values('0112037','CULTIVO DE CAMOTE');
insert into actividadbanxico values('0112045','CULTIVO DE CEBOLLA');
insert into actividadbanxico values('0112053','CULTIVO DE CHILE');
insert into actividadbanxico values('0112061','CULTIVO DE ESPARRAGO');
insert into actividadbanxico values('0112079','CULTIVO DE FRIJOL');
insert into actividadbanxico values('0112087','CULTIVO DE GARBANZO');
insert into actividadbanxico values('0112095','CULTIVO DE JITOMATE');
insert into actividadbanxico values('0112102','CULTIVO DE LENTEJA');
insert into actividadbanxico values('0112110','CULTIVO DE NOPAL');
insert into actividadbanxico values('0112128','CULTIVO DE OTRAS HORTALIZAS');
insert into actividadbanxico values('0112136','CULTIVO DE PAPA');
insert into actividadbanxico values('0112144','CULTIVO DE REMOLACHA');
insert into actividadbanxico values('0112152','CULTIVO DE TOMATE');
insert into actividadbanxico values('0112160','CULTIVO DE YUCA');
insert into actividadbanxico values('0113019','CULTIVO DE ALFALFA');
insert into actividadbanxico values('0119017','CULTIVO DE FRESA');
insert into actividadbanxico values('0119025','CULTIVO DE MELON');
insert into actividadbanxico values('0119033','CULTIVO DE PIÐA');
insert into actividadbanxico values('0119041','CULTIVO DE SANDIA');
insert into actividadbanxico values('0121012','CULTIVO DE ALGODON');
insert into actividadbanxico values('0122010','CULTIVO DE CAÐA DE AZUCAR');
insert into actividadbanxico values('0123018','CULTIVO DE TABACO');
insert into actividadbanxico values('0124016','CULTIVO DE AJONJOLI');
insert into actividadbanxico values('0124024','CULTIVO DE CACAHUATE');
insert into actividadbanxico values('0124032','CULTIVO DE CARTAMO');
insert into actividadbanxico values('0124040','CULTIVO DE NUEZ');
insert into actividadbanxico values('0124058','CULTIVO DE OLIVO');
insert into actividadbanxico values('0129016','CULTIVO DE ESPECIAS');
insert into actividadbanxico values('0129024','CULTIVO DE OTRAS SEMILLAS');
insert into actividadbanxico values('0129032','CULTIVO DE SEMILLAS MEJORADAS');
insert into actividadbanxico values('0129040','CULTIVO DE VAINILLA');
insert into actividadbanxico values('0131011','CULTIVO DE FLORES Y PLANTAS DE ORNATO');
insert into actividadbanxico values('0141010','CULTIVO DE CAFE');
insert into actividadbanxico values('0142018','CULTIVO DE AHUACATE');
insert into actividadbanxico values('0142026','CULTIVO DE DURAZNO');
insert into actividadbanxico values('0142034','CULTIVO DE GUAYABA');
insert into actividadbanxico values('0142042','CULTIVO DE LIMON');
insert into actividadbanxico values('0142050','CULTIVO DE MANGO');
insert into actividadbanxico values('0142068','CULTIVO DE MANZANA');
insert into actividadbanxico values('0142076','CULTIVO DE NARANJA');
insert into actividadbanxico values('0142084','CULTIVO DE OTROS ARBOLES FRUTALES');
insert into actividadbanxico values('0142092','CULTIVO DE PAPAYA');
insert into actividadbanxico values('0142109','CULTIVO DE PLATANO');
insert into actividadbanxico values('0142117','CULTIVO DE TAMARINDO');
insert into actividadbanxico values('0142125','CULTIVO DE TORONJA');
insert into actividadbanxico values('0143016','CULTIVO DE VID');
insert into actividadbanxico values('0144014','CULTIVO DE HENEQUEN');
insert into actividadbanxico values('0144022','CULTIVO DE LINO');
insert into actividadbanxico values('0144030','CULTIVO DE OTRAS FIBRAS DURAS');
insert into actividadbanxico values('0145012','CULTIVO DE AGAVE O MEZCAL');
insert into actividadbanxico values('0145020','CULTIVO DE MAGUEY');
insert into actividadbanxico values('0146010','CULTIVO DE COPRA');
insert into actividadbanxico values('0147018','CULTIVO DE CACAO');
insert into actividadbanxico values('0149014','OTROS CULTIVOS PERMANENTES');
insert into actividadbanxico values('0149907','USUARIOS MENORES DE AGRICULTURA');
insert into actividadbanxico values('0149915','CARTERA AGRICOLA DE ESTADOS ANALITICOS');
insert into actividadbanxico values('0191015','IRRIGACION DE TIERRAS');
insert into actividadbanxico values('0191023','PREPARACION DE TIERRAS DE CULTIVO Y OTROS SERVICIO');
insert into actividadbanxico values('0211011','CRIA Y EXPLOTACION DE GANADO VACUNO PARA CARNE');
insert into actividadbanxico values('0212019','CRIA Y EXPLOTACION DE GANADO VACUNO PARA LECHE');
insert into actividadbanxico values('0213017','CRIA DE GANADO DE LIDIA');
insert into actividadbanxico values('0214015','CRIA DE GANADO CABALLAR');
insert into actividadbanxico values('0219015','CRIA DE OTROS EQUINOS Y GANADO PARA EL TRABAJO');
insert into actividadbanxico values('0219908','USUARIOS MENORES DE GANADERIA');
insert into actividadbanxico values('0219916','CARTERA GANADERA DE ESTADOS ANALITICOS');
insert into actividadbanxico values('0221010','CRIA Y EXPLOTACION DE GANADO PORCINO');
insert into actividadbanxico values('0222018','CRIA Y EXPLOTACION DE GANADO OVINO');
insert into actividadbanxico values('0223016','CRIA Y EXPLOTACION DE GANADO CAPRINO');
insert into actividadbanxico values('0231019','CRIA Y EXPLOTACION DE GALLINA PARA PRODUCCION DE H');
insert into actividadbanxico values('0232017','CRIA Y EXPLOTACION DE POLLOS');
insert into actividadbanxico values('0233015','CRIA Y EXPLOTACION DE OTRAS AVES PARA ALIMENTACION');
insert into actividadbanxico values('0241018','CRIA Y EXPLOTACION DE ABEJAS');
insert into actividadbanxico values('0251017','CRIA Y EXPLOTACION DE CONEJOS Y LIEBRES');
insert into actividadbanxico values('0259011','CRIA Y EXPLOTACION');
insert into actividadbanxico values('0259029','CRIA Y EXPLOTACION DE GUSANO DE SEDA');
insert into actividadbanxico values('0291013','FORMACION DE PRADERAS Y POTREROS ARTIFICIALES');
insert into actividadbanxico values('0291021','INSEMINACION ARTIFICIAL Y OTROS SERVICIOS DE GANAD');
insert into actividadbanxico values('0311019','PLANTACION Y REFORESTACION');
insert into actividadbanxico values('0312017','EXTRACCION DE TRONCOS PARA ASERRADEROS Y PARA PULP');
insert into actividadbanxico values('0313015','EXTRACCION DE CARBON VEGETAL');
insert into actividadbanxico values('0321018','EXTRACCION DE CHICLE');
insert into actividadbanxico values('0322016','EXPLOTACION DE CANDELILLA');
insert into actividadbanxico values('0322024','EXPLOTACION DE HULE');
insert into actividadbanxico values('0322032','EXTRACCION DE COLOFONIA');
insert into actividadbanxico values('0322040','EXTRACCION DE OTRAS RESINAS');
insert into actividadbanxico values('0323014','EXPLOTACION DE RAICES');
insert into actividadbanxico values('0323022','EXTRACCION DE ALQUITRAN VEGETAL');
insert into actividadbanxico values('0323030','EXTRACCION DE TREMENTINA');
insert into actividadbanxico values('0329012','CULTIVO Y EXPLOTACION DE PALMA Y LECHUGUILLA');
insert into actividadbanxico values('0329020','EXPLOTACION DE BARBASCO,ARBORESCENTES Y ARBUSTOS');
insert into actividadbanxico values('0329905','USUARIOS MENORES DE SILVICULTURA, PESCA Y PRESERVA');
insert into actividadbanxico values('0329913','CARTERA SILVICOLA DE ESTADOS ANALITICOS');
insert into actividadbanxico values('0391011','SERVICIOS DE CORTADO ESTIMACION DEL VOLUMEN DE MAD');
insert into actividadbanxico values('0411017','CAPTURA DE ATUN BONITO BARRILETE Y SIMILARES');
insert into actividadbanxico values('0412015','CAPTURA DE SARDINA Y SIMILARES');
insert into actividadbanxico values('0413013','CAPTURA DE TIBURON CAZON RAYA Y SIMILARES');
insert into actividadbanxico values('0419011','CAPTURA DE OTROS PECES EN ESTUARIOS, COSTAS O ALTA');
insert into actividadbanxico values('0419912','CARTERA PESQUERA DE ESTADOS ANALITICOS');
insert into actividadbanxico values('0421016','CAPTURA DE CAMARON');
insert into actividadbanxico values('0422014','CAPTURA DE OSTION');
insert into actividadbanxico values('0429010','CAPTURA DE OTROS CRUSTACEOS Y MOLUSCOS MARINOS');
insert into actividadbanxico values('0431015','CAPTURA DE TORTUGA Y OTROS REPTILES MARINOS');
insert into actividadbanxico values('0439019','CAPTURA DE MAMIFEROS ANFIBIOS Y DIVERSOS INVERTEBR');
insert into actividadbanxico values('0441014','RECOLECCION DE CONCHAS HUEVOS CORALES ESPONJAS Y P');
insert into actividadbanxico values('0442012','RECOLECCION DE ALGAS Y OTRAS PLANTAS ACUATICAS');
insert into actividadbanxico values('0451013','CAPTURA DE PECES EN RIOS, LAGOS Y ESTUARIOS');
insert into actividadbanxico values('0452011','CAPTURA DE CRUSTACEOS MOLUSCOS REPTILES ANFIBIOS Y');
insert into actividadbanxico values('0459017','CRIA Y EXPLOTACION DE OSTRAS');
insert into actividadbanxico values('0459025','CRIA Y EXPLOTACION DE PECES, OTRAS ESPECIES ANIMAL');
insert into actividadbanxico values('0491019','SERVICIOS DE PESQUERIAS MARITIMAS Y DE AGUA DULCE');
insert into actividadbanxico values('0511015','CAPTURA Y PRESERVACION DE ESPECIES ANIMALES SALVAJ');
insert into actividadbanxico values('1111012','EXTRACCION Y BENEFICIO DE CARBON MINERAL Y GRAFITO');
insert into actividadbanxico values('1211010','EXPLORACION DE PETROLEO POR COMPAÐIAS');
insert into actividadbanxico values('1211028','EXTRACCION DE PETROLEO CRUDO Y GAS NATURAL');
insert into actividadbanxico values('1211903','USUARIOS MENORES DE PETROLEO');
insert into actividadbanxico values('1211911','CARTERA PETROLERA DE ESTADOS ANALITICOS');
insert into actividadbanxico values('1311018','EXTRACCION Y BENEFICIO DE MINERAL DE HIERRO');
insert into actividadbanxico values('1321017','EXTRACCION Y BENEFICIO DE ORO PLATA Y OTROS METALE');
insert into actividadbanxico values('1322015','EXTRACCION Y BENEFICIO DE MERCURIO Y ANTIMONIO');
insert into actividadbanxico values('1329011','EXTRACCION Y BENEFICIO DE COBRE, PLOMO, ZINC Y OTR');
insert into actividadbanxico values('1329904','USUARIOS MENORES DE MINERIA');
insert into actividadbanxico values('1329912','CARTERA MINERA DE ESTADOS ANALITICOS');
insert into actividadbanxico values('1411016','EXTRACCION Y BENEFICIO DE PIEDRA');
insert into actividadbanxico values('1412014','EXTRACCION DE YESO');
insert into actividadbanxico values('1413012','EXTRACCION Y BENEFICIO DE ARENA Y GRAVA');
insert into actividadbanxico values('1419010','EXTRACCION Y BENEFICIO DE OTROS MATERIALES PARA CO');
insert into actividadbanxico values('1421015','EXTRACCION Y BENEFICIO DE ARCILLAS REFRACTARIAS');
insert into actividadbanxico values('1431014','EXTRACCION Y BENEFICIO DE BARITA Y ROCA FOSFORICA');
insert into actividadbanxico values('1432012','EXTRACCION Y BENEFICIO DE FLUORITA');
insert into actividadbanxico values('1433010','EXTRACCION Y BENEFICIO DE SILICE');
insert into actividadbanxico values('1439018','EXTRACCION Y BENEFICIO DE OTROS MINERALES NO METAL');
insert into actividadbanxico values('1511014','EXPLOTACION DE SAL MARINA Y DE YACIMIENTOS');
insert into actividadbanxico values('2011013','DESHIDRATACION DE FRUTAS');
insert into actividadbanxico values('2012011','EMPACADORA DE CONSERVAS ALIMENTICIAS');
insert into actividadbanxico values('2012029','EMPACADORA DE FRUTAS Y LEGUMBRES');
insert into actividadbanxico values('2012037','FABRICACION DE CONCENTRADOS DE FRUTAS');
insert into actividadbanxico values('2012045','FABRICACION DE ENCURTIDOS');
insert into actividadbanxico values('2013019','FABRICACION DE ATES');
insert into actividadbanxico values('2013027','FABRICACION DE QUESO Y MIEL DE TUNA');
insert into actividadbanxico values('2014017','FABRICACION DE SALSAS');
insert into actividadbanxico values('2021012','MOLINO DE TRIGO');
insert into actividadbanxico values('2022010','MOLINO DE MAIZ');
insert into actividadbanxico values('2023018','MOLINO DE NIXTAMAL');
insert into actividadbanxico values('2024016','MOLINO DE ARROZ');
insert into actividadbanxico values('2025014','BENEFICIO DE CAFE EXCEPTO MOLIENDA Y TOSTADO');
insert into actividadbanxico values('2026012','MOLINO Y TOSTADOR DE CAFE');
insert into actividadbanxico values('2027010','EMPACADORA DE TE');
insert into actividadbanxico values('2028018','BENEFICIO DE ARROZ EXCEPTO MOLIENDA');
insert into actividadbanxico values('2028026','DESCASCARADO Y TOSTADO DE CACAHUATE Y NUEZ');
insert into actividadbanxico values('2028034','DESCASCARADORA Y TOSTADORA DE SEMILLA DE CALABAZA');
insert into actividadbanxico values('2028042','MOLINO PARA OTROS GRANOS EXCEPTO CEREALES');
insert into actividadbanxico values('2029016','MOLINO DE AVENA');
insert into actividadbanxico values('2029024','MOLINO DE CEBADA');
insert into actividadbanxico values('2029032','MOLINO DE OTROS CEREALES');
insert into actividadbanxico values('2031011','FABRICACION DE MARQUETAS Y ESTUCHADOS DE AZUCAR');
insert into actividadbanxico values('2031029','INGENIO AZUCARERO');
insert into actividadbanxico values('2032019','FABRICACION DE PILONCILLO');
insert into actividadbanxico values('2033017','DESTILACION DE ALCOHOL ETILICO');
insert into actividadbanxico values('2041010','RASTRO');
insert into actividadbanxico values('2049014','EMPACADORA DE CARNE');
insert into actividadbanxico values('2049022','FABRICACION DE CARNES FRIAS Y EMBUTIDOS');
insert into actividadbanxico values('2049030','REFRIGERACION DE CARNES');
insert into actividadbanxico values('2051019','FABRICACION Y REHIDRATACION DE LECHE');
insert into actividadbanxico values('2051027','PASTEURIZACION HOMOGENEIZACION Y ENVASADO DE LECHE');
insert into actividadbanxico values('2052017','FABRICACION DE CREMA MANTEQUILLA Y QUESO');
insert into actividadbanxico values('2053015','FABRICACION DE LECHE CONDENSADA EVAPORADA Y PULVER');
insert into actividadbanxico values('2054013','FABRICACION DE GELATINAS');
insert into actividadbanxico values('2054021','FABRICACION DE GRENETINA');
insert into actividadbanxico values('2059013','FABRICACION DE CAJETAS YOGOURTS Y OTROS PRODUCTOS');
insert into actividadbanxico values('2061018','CONGELADORA DE PRODUCTOS MARINOS');
insert into actividadbanxico values('2061026','EMPACADORA DE OTROS MARISCOS');
insert into actividadbanxico values('2061034','EMPACADORA DE PESCADO');
insert into actividadbanxico values('2071017','FABRICACION DE PAN Y PASTELES');
insert into actividadbanxico values('2072015','FABRICACION DE CONOS PARA NIEVE');
insert into actividadbanxico values('2072023','FABRICACION DE GALLETAS');
insert into actividadbanxico values('2072031','FABRICACION DE PASTAS ALIMENTICIAS');
insert into actividadbanxico values('2081016','FABRICACION DE CHOCOLATES');
insert into actividadbanxico values('2082014','FABRICACION DE DULCES BOMBONES Y CONFITES');
insert into actividadbanxico values('2083012','FABRICACION DE GOMA DE MASCAR');
insert into actividadbanxico values('2084010','TRATAMIENTO Y ENVASE DE MIEL DE ABEJA');
insert into actividadbanxico values('2089010','FABRICACION DE JARABES');
insert into actividadbanxico values('2091015','FABRICACION DE ACEITES VEGETALES COMESTIBLES');
insert into actividadbanxico values('2091023','FABRICACION DE MANTECAS VEGETALES COMESTIBLES');
insert into actividadbanxico values('2092013','FABRICACION DE ALMIDON');
insert into actividadbanxico values('2092021','FABRICACION DE LEVADURAS');
insert into actividadbanxico values('2093011','TORTILLERIA');
insert into actividadbanxico values('2094019','FABRICACION DE FRITURAS');
insert into actividadbanxico values('2094027','FABRICACION DE OTROS PREPARADOS ALIMENTICIOS DERIV');
insert into actividadbanxico values('2095017','FABRICACION DE VINAGRE');
insert into actividadbanxico values('2095025','REFINACION DE SAL');
insert into actividadbanxico values('2096015','FABRICACION DE HIELO');
insert into actividadbanxico values('2097013','FABRICACION DE HELADOS NIEVES Y PALETAS');
insert into actividadbanxico values('2098011','DESHIDRATACION DE PLANTAS PARA FORRAJES');
insert into actividadbanxico values('2098029','FABRICACION DE ALIMENTO PARA GANADO Y OTROS ANIMAL');
insert into actividadbanxico values('2098037','FABRICACION DE ALIMENTOS PARA AVES');
insert into actividadbanxico values('2099019','EMPACADORA DE ESPECIAS');
insert into actividadbanxico values('2099027','FABRICACION DE ACEITES Y MANTECAS ANIMALES COMESTI');
insert into actividadbanxico values('2099035','FABRICACION DE HARINA DE PESCADO');
insert into actividadbanxico values('2099043','FABRICACION DE OTROS PRODUCTOS ALIMENTICIOS');
insert into actividadbanxico values('2099051','FABRICACION DE PASTAS PARA GUISOS');
insert into actividadbanxico values('2111011','FABRICACION DE TEQUILA Y MEZCAL');
insert into actividadbanxico values('2112019','FABRICACION DE AGUARDIENTE DE CAÐA');
insert into actividadbanxico values('2113017','FABRICACION DE SOTOL');
insert into actividadbanxico values('2114015','FABRICACION DE OTROS AGUARDIENTES NO DE CAÐA');
insert into actividadbanxico values('2114023','FABRICACION DE VINOS Y OTROS LICORES');
insert into actividadbanxico values('2115013','ELABORACION DE PULQUE');
insert into actividadbanxico values('2119015','FABRICACION DE SIDRA, CHAMPAÐA Y OTRAS BEBIDAS FER');
insert into actividadbanxico values('2121010','FABRICACION DE MALTA');
insert into actividadbanxico values('2122018','FABRICACION DE CERVEZA');
insert into actividadbanxico values('2131019','EMBOTELLADO DE AGUAS MINERALES');
insert into actividadbanxico values('2131027','FABRICACION DE BEBIDAS GASEOSAS');
insert into actividadbanxico values('2131035','FABRICACION DE REFRESCOS DE FRUTAS NATURALES');
insert into actividadbanxico values('2131043','PURIFICACION DE AGUA, EXCEPTO CAPTACION TRATAMIENT');
insert into actividadbanxico values('2211019','DESECADO DE TABACO');
insert into actividadbanxico values('2212017','FABRICACION DE CIGARROS');
insert into actividadbanxico values('2219013','FABRICACION DE PUROS');
insert into actividadbanxico values('2219021','PICADO DE TABACO');
insert into actividadbanxico values('2311017','DESFIBRACION DE ALGODON');
insert into actividadbanxico values('2311025','DESPEPITE DE ALGODON');
insert into actividadbanxico values('2311033','COMPRESORA DE ALGODON');
insert into actividadbanxico values('2312015','BENEFICIO DE LANAS');
insert into actividadbanxico values('2312023','BENEFICIO DE OTRAS FIBRAS TEXTILES');
insert into actividadbanxico values('2312031','FABRICACION DE HILADOS Y TEJIDOS DE ALGODON');
insert into actividadbanxico values('2312049','FABRICACION DE HILADOS Y TEJIDOS DE LANA');
insert into actividadbanxico values('2313013','FABRICACION DE HILOS PARA COSER');
insert into actividadbanxico values('2313021','ACABADO DE HILOS');
insert into actividadbanxico values('2313039','FABRICACION DE OTROS HILADOS Y TEJIDOS NO SINTETIC');
insert into actividadbanxico values('2314011','FABRICACION DE ESTAMBRES');
insert into actividadbanxico values('2315019','FABRICACION DE SARAPES Y COBIJAS');
insert into actividadbanxico values('2315027','FABRICACION DE CASIMIRES Y PAÐOS');
insert into actividadbanxico values('2316017','FABRICACION DE TOALLAS');
insert into actividadbanxico values('2316025','FABRICACION DE COLCHAS');
insert into actividadbanxico values('2317015','FABRICACION DE HILADOS Y TEJIDOS DE SEDA');
insert into actividadbanxico values('2317023','FABRICACION DE OTROS ARTICULOS DE LANA');
insert into actividadbanxico values('2317031','FABRICACION DE OTRAS TELAS MIXTAS  DE FIBRAS BLAND');
insert into actividadbanxico values('2318013','FABRICACION DE CINTAS AGUJETAS Y LISTONES');
insert into actividadbanxico values('2318021','FABRICACION DE ENCAJES');
insert into actividadbanxico values('2318039','FABRICACION DE TELAS ELASTICAS');
insert into actividadbanxico values('2319011','ACABADO DE TELAS');
insert into actividadbanxico values('2321016','FABRICACION DE CALCETINES');
insert into actividadbanxico values('2321024','FABRICACION DE MEDIAS');
insert into actividadbanxico values('2322014','FABRICACION DE SUETERES');
insert into actividadbanxico values('2329010','FABRICACION DE HILADOS Y TEJIDOS DE OTRAS FIBRAS S');
insert into actividadbanxico values('2331015','DESFIBRACION DE HENEQUEN');
insert into actividadbanxico values('2332013','FABRICACION DE HILADOS Y TEJIDOS DE HENEQUEN');
insert into actividadbanxico values('2333011','FABRICACION DE ARTICULOS DE PALMA Y TULE');
insert into actividadbanxico values('2333029','FABRICACION DE TEJIDOS Y TORCIDOS DE PALMA');
insert into actividadbanxico values('2333037','FABRICACION DE TEJIDOS Y TORCIDOS DE IXTLE');
insert into actividadbanxico values('2339019','FABRICACION DE HILADOS Y TEJIDOS DE YUTE');
insert into actividadbanxico values('2339027','FABRICACION DE HILADOS Y TEJIDOS DE FIBRA DE COCO');
insert into actividadbanxico values('2391019','FABRICACION DE ARTICULOS DE LONA');
insert into actividadbanxico values('2391027','FABRICACION DE LONA');
insert into actividadbanxico values('2391035','FABRICACION DE TELAS IMPERMEABLES');
insert into actividadbanxico values('2392017','FABRICACION DE TAPETES Y ALFOMBRAS');
insert into actividadbanxico values('2392025','FABRICACION DE TELAS PARA TAPICERIA');
insert into actividadbanxico values('2393015','FABRICACION DE ENTRETELAS Y FIELTROS');
insert into actividadbanxico values('2394013','BENEFICIO DE PELO Y CERDA PARA LA INDUSTRIA TEXTIL');
insert into actividadbanxico values('2394021','FABRICACION DE BORRAS Y ESTOPAS');
insert into actividadbanxico values('2394039','FABRICACION DE OTROS ARTICULOS DE ALGODON');
insert into actividadbanxico values('2411015','FABRICACION DE VESTIDOS Y OTRAS PRENDAS EXTERIORES');
insert into actividadbanxico values('2411023','TALLER DE CONFECCION DE VESTIDOS');
insert into actividadbanxico values('2412013','FABRICACION DE OTRAS PRENDAS EXTERIORES DE VESTIR');
insert into actividadbanxico values('2412021','FABRICACION DE TRAJES PARA CABALLERO');
insert into actividadbanxico values('2412039','TALLER DE SASTRERIA');
insert into actividadbanxico values('2413011','FABRICACION DE UNIFORMES');
insert into actividadbanxico values('2414019','FABRICACION DE CAMISAS');
insert into actividadbanxico values('2415017','FABRICACION DE OTRAS PRENDAS EXTERIORES DE VESTIR');
insert into actividadbanxico values('2416015','FABRICACION DE CORBATAS');
insert into actividadbanxico values('2416023','FABRICACION DE GUANTES');
insert into actividadbanxico values('2416031','FABRICACION DE PAÐUELOS PAÐOLETAS Y MASCADAS');
insert into actividadbanxico values('2417013','FABRICACION DE CACHUCHAS Y GORRAS');
insert into actividadbanxico values('2417021','FABRICACION DE SOMBREROS EXCEPTO DE PALMA');
insert into actividadbanxico values('2418011','FABRICACION DE SOMBREROS DE PALMA');
insert into actividadbanxico values('2419019','FABRICACION DE CHAMARRAS Y ABRIGOS');
insert into actividadbanxico values('2419027','FABRICACION DE IMPERMEABLES');
insert into actividadbanxico values('2419035','FABRICACION DE TIRANTES');
insert into actividadbanxico values('2419043','FABRICACION DE MANTONES Y CHALINAS');
insert into actividadbanxico values('2419051','FABRICACION DE REBOZOS Y CINTURONES TEJIDOS DE HIL');
insert into actividadbanxico values('2419069','FABRICACION DE ROPA CON PIEL');
insert into actividadbanxico values('2421014','FABRICACION DE CORSETERIA Y ROPA INTERIOR PARA DAM');
insert into actividadbanxico values('2429018','FABRICACION DE ROPA INTERIOR PARA CABALLERO');
insert into actividadbanxico values('2431013','FABRICACION DE SABANAS');
insert into actividadbanxico values('2431021','FABRICACION DE CORTINAS DE TELA Y MANTELERIA');
insert into actividadbanxico values('2432011','FABRICACION DE CUBREASIENTOS PARA VEHICULOS');
insert into actividadbanxico values('2432029','FABRICACION DE TAPICES PLASTICOS');
insert into actividadbanxico values('2433019','FABRICACION DE ALGODON ABSORBENTE VENDAS TELA ADEH');
insert into actividadbanxico values('2434017','FABRICACION DE ARTICULOS BORDADOS Y DESHILADOS');
insert into actividadbanxico values('2434025','FORRADO DE BOTONES Y HEBILLAS');
insert into actividadbanxico values('2439017','FABRICACION DE BANDERAS Y ADORNOS DE TELA');
insert into actividadbanxico values('2439025','FABRICACION DE COSTALES');
insert into actividadbanxico values('2511013','FABRICACION DE CALZADO PARA DEPORTE EXCEPTO DE PLA');
insert into actividadbanxico values('2512011','FABRICACION DE ALPARGATAS BABUCHAS Y PANTUFLAS');
insert into actividadbanxico values('2512029','FABRICACION DE GUARACHES Y SANDALIAS');
insert into actividadbanxico values('2519017','FABRICACION DE CALZADO DE CUERO O PIEL');
insert into actividadbanxico values('2521012','CURTIDURIA');
insert into actividadbanxico values('2521020','PREPARACION DE VISCERAS PARA INDUSTRIAS NO ALIMENT');
insert into actividadbanxico values('2529016','FABRICACION DE CEPILLOS Y PLUMEROS');
insert into actividadbanxico values('2529024','FABRICACION DE ARTICULOS DE CUERO PARA VIAJE');
insert into actividadbanxico values('2529032','FABRICACION DE ARTICULOS DE CUERO Y HUESO');
insert into actividadbanxico values('2529040','FABRICACION DE ARTICULOS DE CUERO Y PIEL PARA ZAPA');
insert into actividadbanxico values('2529058','FABRICACION DE ARTICULOS TEJIDOS DE CUERO');
insert into actividadbanxico values('2529066','FABRICACION DE BANDAS Y CORREAS DE CUERO');
insert into actividadbanxico values('2529074','FABRICACION DE BOLSAS Y CARTERAS DE CUERO');
insert into actividadbanxico values('2529082','FABRICACION DE BROCHAS Y PINCELES');
insert into actividadbanxico values('2529090','FABRICACION DE FORNITURAS MILITARES DE CUERO');
insert into actividadbanxico values('2529107','FABRICACION DE OTROS ARTICULOS DE CUERO');
insert into actividadbanxico values('2529115','TALABARTERIA');
insert into actividadbanxico values('2611011','ASERRADERO');
insert into actividadbanxico values('2611029','BENEFICIO DE MADERAS (DESFLEMADO ESTUFADO CEPILLAD');
insert into actividadbanxico values('2612019','FABRICACION DE TRIPLAY Y OTROS AGLOMERADOS DE MADE');
insert into actividadbanxico values('2621010','FABRICACION DE CAJAS Y EMPAQUES DE MADERA');
insert into actividadbanxico values('2621028','FABRICACION DE TONELES Y BARRICAS DE MADERA');
insert into actividadbanxico values('2622018','FABRICACION DE ARTICULOS DE PALMA VARA CARRIZO MIM');
insert into actividadbanxico values('2631019','FABRICACION DE ATAUDES DE MADERA');
insert into actividadbanxico values('2632017','FABRICACION DE JUNTAS Y EMPAQUES DE CORCHO');
insert into actividadbanxico values('2632025','FABRICACION DE OTROS ARTICULOS DE CORCHO');
insert into actividadbanxico values('2632033','FABRICACION DE ASBESTOS Y CORCHOS AISLANTES');
insert into actividadbanxico values('2633015','FABRICACION DE DUELAS Y OTROS MATERIALES DE MADERA');
insert into actividadbanxico values('2633023','FABRICACION DE PUERTAS Y VENTANAS DE MADERA');
insert into actividadbanxico values('2639013','FABRICACION DE CARROCERIAS Y REDILAS DE MADERA');
insert into actividadbanxico values('2639021','FABRICACION DE MANGOS DE MADERA');
insert into actividadbanxico values('2639039','FABRICACION DE OTROS ARTICULOS DE MADERA');
insert into actividadbanxico values('2711019','FABRICACION DE MUEBLES DE MADERA');
insert into actividadbanxico values('2711027','FABRICACION DE MUEBLES DE MATERIAL SINTETICO');
insert into actividadbanxico values('2712017','FABRICACION DE PERSIANAS DE MADERA');
insert into actividadbanxico values('2713015','FABRICACION DE ALMOHADAS Y COJINES');
insert into actividadbanxico values('2713023','FABRICACION DE COLCHONES Y COLCHONETAS');
insert into actividadbanxico values('2719013','FABRICACION DE MARCOS Y MOLDURAS DE MADERA');
insert into actividadbanxico values('2811017','FABRICACION DE PAPEL');
insert into actividadbanxico values('2811025','FABRICACION DE PAPEL PARA CIGARROS');
insert into actividadbanxico values('2811033','FABRICACION DE PASTA DE CELULOSA');
insert into actividadbanxico values('2811041','FABRICACION DE PASTA O PULPA PARA PAPEL');
insert into actividadbanxico values('2812015','FABRICACION DE CARTON');
insert into actividadbanxico values('2821016','FABRICACION DE SACOS Y BOLSAS DE PAPEL PARA ENVASE');
insert into actividadbanxico values('2822014','FABRICACION DE ENVASES DE CARTON');
insert into actividadbanxico values('2829010','FABRICACION DE OTROS ARTICULOS DE CARTON');
insert into actividadbanxico values('2829028','FABRICACION DE OTROS ARTICULOS DE PAPEL');
insert into actividadbanxico values('2911015','EDICION DE PERIODICOS Y REVISTAS');
insert into actividadbanxico values('2912005','EDICION DE LIBROS Y SIMILARES');
insert into actividadbanxico values('2912013','EDICION DE LIBROS');
insert into actividadbanxico values('2921014','ENCUADERNACION');
insert into actividadbanxico values('2921022','FABRICACION DE FORMULARIOS Y FORMAS CONTINUAS');
insert into actividadbanxico values('2921030','FABRICACION DE LIBRETAS CUADERNOS Y HOJAS PARA ENC');
insert into actividadbanxico values('2921048','FOTOCOPIADO');
insert into actividadbanxico values('2921056','IMPRENTA ( TIPOGRAFIA )');
insert into actividadbanxico values('2921064','IMPRESION MEDIANTE CILINDROS DE CAUCHO');
insert into actividadbanxico values('2921072','IMPRESION MEDIANTE CILINDROS (ROTOGRABADO)');
insert into actividadbanxico values('2929018','FABRICACION DE CALCOMANIAS');
insert into actividadbanxico values('2929026','FABRICACION DE TIPOS PARA IMPRENTA');
insert into actividadbanxico values('2929034','GRABADO E IMPRESION EN PIEDRA, VIDRIO Y OTROS MATE');
insert into actividadbanxico values('2929042','GRABADO E IMPRESION FOTOMECANICA MEDIANTE AGUA FUE');
insert into actividadbanxico values('2929050','GRABADO EN METAL (FABRICACION DE CLICHES Y FOTOGRA');
insert into actividadbanxico values('3011012','FABRICACION DE ANIL');
insert into actividadbanxico values('3011020','FABRICACION DE ANILINAS');
insert into actividadbanxico values('3011038','FABRICACION DE OTRAS MATERIAS COLORANTES');
insert into actividadbanxico values('3012010','FABRICACION DE GAS ACETILENO');
insert into actividadbanxico values('3013018','FABRICACION DE ACIDOS INDUSTRIALES');
insert into actividadbanxico values('3013026','FABRICACION DE OTRAS SUBSTANCIAS QUIMICAS BASICAS');
insert into actividadbanxico values('3013034','FABRICACION DE PRODUCTOS AMONIACALES');
insert into actividadbanxico values('3013042','FABRICACION DE SOSA');
insert into actividadbanxico values('3021011','FABRICACION DE ABONOS Y FERTILIZANTES QUIMICOS');
insert into actividadbanxico values('3022019','FABRICACION DE INSECTICIDAS Y PLAGUICIDAS');
insert into actividadbanxico values('3031010','FABRICACION DE HULE ESPUMA');
insert into actividadbanxico values('3032018','FABRICACION DE FIBRAS SINTETICAS');
insert into actividadbanxico values('3041019','FABRICACION DE PINTURAS, BARNICES Y LACAS');
insert into actividadbanxico values('3051018','FABRICACION DE ALGODON ESTERILIZADO, GASAS Y VENDA');
insert into actividadbanxico values('3051026','FABRICACION DE OTROS PRODUCTOS FARMACEUTICOS Y MED');
insert into actividadbanxico values('3051034','FABRICACION DE OXIGENO MEDICINAL');
insert into actividadbanxico values('3061017','FABRICACION DE DENTIFRICO');
insert into actividadbanxico values('3061025','FABRICACION DE JABON Y DETERGENTE');
insert into actividadbanxico values('3062015','FABRICACION DE PERFUMES Y COSMETICOS');
insert into actividadbanxico values('3071016','FABRICACION DE ESENCIAS');
insert into actividadbanxico values('3072014','FABRICACION Y REFINACION DE SEBO GRASAS Y ACEITES');
insert into actividadbanxico values('3072022','FUNDICION DE SEBO');
insert into actividadbanxico values('3072030','HIDROGENADORA DE PRODUCTOS DIVERSOS');
insert into actividadbanxico values('3091014','FABRICACION DE COLAS Y PEGAMENTOS');
insert into actividadbanxico values('3091022','FABRICACION DE IMPERMEABILIZANTES');
insert into actividadbanxico values('3092012','FABRICACION DE CERA PULIMENTOS Y ABRILLANTADORES');
insert into actividadbanxico values('3092020','FABRICACION DE DESINFECTANTES Y DESODORIZANTES');
insert into actividadbanxico values('3092038','FABRICACION DE GRASAS Y CREMAS LUSTRADORAS');
insert into actividadbanxico values('3092046','FABRICACION DE LANOLINA');
insert into actividadbanxico values('3093010','FABRICACION DE AGUARRAS');
insert into actividadbanxico values('3094018','FABRICACION DE CERILLOS Y FOSFOROS');
insert into actividadbanxico values('3095016','FABRICACION DE OTROS ARTICULOS DE CERA');
insert into actividadbanxico values('3095024','FABRICACION DE VELAS VELADORAS Y CIRIOS');
insert into actividadbanxico values('3096014','FABRICACION DE TINTAS PARA IMPRESION');
insert into actividadbanxico values('3097012','FABRICACION DE DINAMITA');
insert into actividadbanxico values('3097020','FABRICACION DE MECHAS PARA MINAS');
insert into actividadbanxico values('3097038','FABRICACION DE OTROS EXPLOSIVOS');
insert into actividadbanxico values('3097046','FABRICACION DE POLVORA');
insert into actividadbanxico values('3097054','FABRICACION DE PRODUCTOS PIROTECNICOS');
insert into actividadbanxico values('3099018','FABRICACION DE ARTICULOS DE BAQUELITA');
insert into actividadbanxico values('3099026','FABRICACION DE DESINCRUSTANTES');
insert into actividadbanxico values('3099034','FABRICACION DE HIELO SECO');
insert into actividadbanxico values('3099042','INDUSTRIALIZACION DE BASURA');
insert into actividadbanxico values('3111010','FABRICACION DE GASOLINA Y OTROS PRODUCTOS DERIVADO');
insert into actividadbanxico values('3112018','FABRICACION DE PRODUCTOS PETROQUIMICOS BASICOS');
insert into actividadbanxico values('3113016','FABRICACION DE ACEITES Y LUBRICANTES');
insert into actividadbanxico values('3121019','FABRICACION DE COQUE Y OTROS DERIVADOS DEL CARBON');
insert into actividadbanxico values('3122017','FABRICACION DE MATERIALES ASFALTICOS PARA PAVIMENT');
insert into actividadbanxico values('3211018','FABRICACION DE LLANTAS Y CAMARAS PARA VEHICULOS');
insert into actividadbanxico values('3212016','REGENERACION DE HULE');
insert into actividadbanxico values('3212024','VULCANIZACION DE LLANTAS Y CAMARAS');
insert into actividadbanxico values('3219012','FABRICACION DE ARTICULOS CON HULE USADO');
insert into actividadbanxico values('3219020','FABRICACION DE LINOLEO');
insert into actividadbanxico values('3219038','FABRICACION DE OTROS ARTICULOS DE HULE');
insert into actividadbanxico values('3221017','FABRICACION DE LAMINAS PERFILES TUBOS Y OTROS MATE');
insert into actividadbanxico values('3222015','FABRICACION DE ARTICULOS DE POLIETILENO');
insert into actividadbanxico values('3222023','FABRICACION DE CELULOIDE Y POLIETILENO');
insert into actividadbanxico values('3223013','FABRICACION DE CALZADO DE PLASTICO');
insert into actividadbanxico values('3223021','FABRICACION DE OTROS JUGUETES DE PLASTICO');
insert into actividadbanxico values('3229011','FABRICACION DE ARTICULOS DE CELULOIDE');
insert into actividadbanxico values('3229029','FABRICACION DE BALONES GLOBOS Y PELOTAS');
insert into actividadbanxico values('3229037','FABRICACION DE BOTONES DE PLASTICO');
insert into actividadbanxico values('3229045','FABRICACION DE OTROS ARTICULOS DE PLASTICO');
insert into actividadbanxico values('3229053','FABRICACION DE OTROS MATERIALES DE PLASTICO');
insert into actividadbanxico values('3229061','FABRICACION DE PEINES PEINETAS Y CEPILLOS PARA USO');
insert into actividadbanxico values('3229079','FABRICACION DE PIELES ARTIFICIALES');
insert into actividadbanxico values('3311016','FABRICACION DE VAJILLAS Y OTROS PRODUCTOS DE ALFAR');
insert into actividadbanxico values('3319010','ELABORACION DE OBJETOS ARTISTICOS DE ALFARERIA Y C');
insert into actividadbanxico values('3319028','FABRICACION DE AZULEJOS');
insert into actividadbanxico values('3319036','FABRICACION DE LOZA Y PORCELANA');
insert into actividadbanxico values('3319044','FABRICACION DE MUEBLES Y ARTICULOS SANITARIOS');
insert into actividadbanxico values('3321015','FABRICACION DE VIDRIO');
insert into actividadbanxico values('3322013','FABRICACION DE CRISTALES PARA AUTOMOVIL');
insert into actividadbanxico values('3322021','FABRICACION DE FIBRA DE VIDRIO');
insert into actividadbanxico values('3323011','FABRICACION DE AMPOLLETAS');
insert into actividadbanxico values('3323029','FABRICACION DE BOTELLAS');
insert into actividadbanxico values('3323037','FABRICACION DE CRISOLES');
insert into actividadbanxico values('3323045','FABRICACION DE OTROS ENVASES DE VIDRIO');
insert into actividadbanxico values('3324019','FABRICACION DE EMPLOMADOS');
insert into actividadbanxico values('3324027','FABRICACION DE ESPEJOS Y LUNAS');
insert into actividadbanxico values('3329019','FABRICACION DE ESFERAS DE VIDRIO');
insert into actividadbanxico values('3329027','FABRICACION DE OBJETOS ARTISTICOS DE VIDRIO Y CRIS');
insert into actividadbanxico values('3329035','FABRICACION DE OTROS OBJETOS DE CRISTAL');
insert into actividadbanxico values('3331014','FABRICACION DE ADOBE');
insert into actividadbanxico values('3331022','FABRICACION DE LADRILLOS');
insert into actividadbanxico values('3331030','FABRICACION DE TEJA Y TUBO DE ARCILLA');
insert into actividadbanxico values('3332012','FABRICACION DE MATERIALES PARA MUROS');
insert into actividadbanxico values('3332020','FABRICACION DE PRODUCTOS REFRACTARIOS');
insert into actividadbanxico values('3341013','FABRICACION DE CEMENTO');
insert into actividadbanxico values('3341021','FABRICACION DE CONCRETO CIENTIFICO');
insert into actividadbanxico values('3341039','FABRICACION DE CONCRETO PARA CONSTRUCCION');
insert into actividadbanxico values('3342011','FABRICACION DE BLOQUES DE CEMENTO');
insert into actividadbanxico values('3342029','FABRICACION DE YESO');
insert into actividadbanxico values('3343019','HORNO DE CAL');
insert into actividadbanxico values('3351012','FABRICACION DE TINACOS DE ASBESTO');
insert into actividadbanxico values('3352010','FABRICACION DE ABRASIVOS');
insert into actividadbanxico values('3352028','FABRICACION DE ESMERILES');
insert into actividadbanxico values('3352036','FABRICACION DE LIJA');
insert into actividadbanxico values('3353018','TALLER DE MARMOLERIA');
insert into actividadbanxico values('3354016','FABRICACION DE MOSAICOS TERRAZOS Y GRANITO');
insert into actividadbanxico values('3354024','FABRICACION DE POSTES Y DURMIENTES DE CONCRETO');
insert into actividadbanxico values('3354032','FABRICACION DE TUBOS DE CONCRETO');
insert into actividadbanxico values('3354909','USUARIOS MENORES DE INDUSTRIA DE PRODUCTOS DE MINE');
insert into actividadbanxico values('3354917','CARTERA DE PRODUCTOS MINERALES NO METALICOS DE EST');
insert into actividadbanxico values('3411014','FABRICACION DE FIERRO ESPONJA');
insert into actividadbanxico values('3411022','FUNDICION DE FIERRO Y ACERO');
insert into actividadbanxico values('3411030','PLANTA METALURGICA');
insert into actividadbanxico values('3411907','USUARIOS MENORES DE INDUSTRIA SIDERURGICA Y DE PRO');
insert into actividadbanxico values('3411915','CARTERA SIDERURGICA Y DE PRODUCTOS METALICOS DE ES');
insert into actividadbanxico values('3412012','FABRICACION DE LAMINAS DE HIERRO Y ACERO');
insert into actividadbanxico values('3412020','FABRICACION DE OTROS ARTICULOS DE LAMINA');
insert into actividadbanxico values('3413010','FABRICACION DE TUBOS DE HIERRO Y ACERO');
insert into actividadbanxico values('3421013','FUNDICION REFINACION LAMINACION EXTRUSION Y ESTIRA');
insert into actividadbanxico values('3422011','FUNDICION LAMINACION EXTRUSION Y ESTIRAJE DE ALUMI');
insert into actividadbanxico values('3423019','FABRICACION DE TUBOS DE ESTAÐO');
insert into actividadbanxico values('3423027','FABRICACION DE EQUIPOS PARA SOLDAR Y SOLDADURAS');
insert into actividadbanxico values('3429017','FUNDICION DE METALES NO FERRUGINOSOS');
insert into actividadbanxico values('3511012','FABRICACION DE CUBIERTOS Y CUCHILLERIA');
insert into actividadbanxico values('3512010','FABRICACION DE UTENSILIOS AGRICOLAS Y HERRAMIENTAS');
insert into actividadbanxico values('3513018','FABRICACION DE REMACHES');
insert into actividadbanxico values('3513026','FABRICACION DE TORNILLOS TUERCAS Y PIJAS');
insert into actividadbanxico values('3514016','FABRICACION DE CLAVOS CADENAS GRAPAS Y TACHUELAS');
insert into actividadbanxico values('3515014','FABRICACION DE CANDADOS');
insert into actividadbanxico values('3515022','FABRICACION DE CERRADURAS');
insert into actividadbanxico values('3516012','FABRICACION DE CORTINAS DE METAL');
insert into actividadbanxico values('3516020','FABRICACION DE JAULAS DE METAL');
insert into actividadbanxico values('3516038','FABRICACION DE OTROS ARTICULOS DE ALUMINIO');
insert into actividadbanxico values('3516046','FABRICACION DE PERFILES PUERTAS Y VENTANAS DE META');
insert into actividadbanxico values('3516054','TALLER DE HERRERIA');
insert into actividadbanxico values('3521011','FABRICACION DE BUTACAS DE METAL');
insert into actividadbanxico values('3521029','FABRICACION DE ESTUFAS');
insert into actividadbanxico values('3521037','FABRICACION DE OTROS MUEBLES DE METAL');
insert into actividadbanxico values('3531010','FABRICACION DE ESTRUCTURAS DE METAL');
insert into actividadbanxico values('3531028','FABRICACION DE TANQUES PARA ENVASADO DE GASES O LI');
insert into actividadbanxico values('3532018','FABRICACION DE CALDERAS TANQUES Y TINACOS DE METAL');
insert into actividadbanxico values('3532026','FABRICACION DE CALENTADORES PARA BAÐO');
insert into actividadbanxico values('3591014','FABRICACION DE ENVASES DE LAMINA');
insert into actividadbanxico values('3591022','TALLER DE HOJALATERIA');
insert into actividadbanxico values('3592012','FABRICACION DE CORCHOLATAS');
insert into actividadbanxico values('3593010','FABRICACION DE ALAMBRADOS Y TELAS DE METAL');
insert into actividadbanxico values('3593028','FABRICACION DE ALAMBRE');
insert into actividadbanxico values('3593036','FABRICACION DE OTROS ARTICULOS DE ALAMBRE');
insert into actividadbanxico values('3594018','FABRICACION DE ARTICULOS DE PELTRE');
insert into actividadbanxico values('3595016','GALVANIZACION DE LAMINA');
insert into actividadbanxico values('3595024','GALVANIZACION DE TUBERIA');
insert into actividadbanxico values('3595032','TALLER DE COBRIZADO');
insert into actividadbanxico values('3595040','TALLER DE CROMADO Y NIQUELADO');
insert into actividadbanxico values('3595058','TALLER DE ESMALTADO');
insert into actividadbanxico values('3596014','FABRICACION DE PIEZAS METALICAS POR FUNDICION Y MO');
insert into actividadbanxico values('3596022','FABRICACION DE TUBOS DE COBRE, PLOMO Y ALUMINIO');
insert into actividadbanxico values('3599018','FABRICACION DE ALFILERES AGUJAS Y BROCHES');
insert into actividadbanxico values('3599026','FABRICACION DE CAJAS FUERTES');
insert into actividadbanxico values('3599034','FABRICACION DE CIERRES AUTOMATICOS DE METAL');
insert into actividadbanxico values('3599042','FABRICACION DE ESPUELAS FRENOS Y ARNESES DE METAL');
insert into actividadbanxico values('3599050','FABRICACION DE HEBILLAS DE METAL');
insert into actividadbanxico values('3599068','FABRICACION DE HOJAS PARA RASURAR');
insert into actividadbanxico values('3599076','FABRICACION DE OJILLOS DE METAL');
insert into actividadbanxico values('3599084','FABRICACION DE OTROS ARTICULOS DE LATON');
insert into actividadbanxico values('3599092','FABRICACION DE OTROS ARTICULOS DE METAL NO CLASIFI');
insert into actividadbanxico values('3599109','FABRICACION DE PASADORES Y HORQUILLAS');
insert into actividadbanxico values('3599117','FABRICACION DE PLANCHAS INDUSTRIALES');
insert into actividadbanxico values('3599125','FABRICACION DE TAPONES DE METAL');
insert into actividadbanxico values('3599133','FABRICACION DE TROQUELES');
insert into actividadbanxico values('3611010','FABRICACION ENSAMBLE Y REPARACION DE VEHICULOS DE');
insert into actividadbanxico values('3611028','FABRICACION DE MAQUINARIA E IMPLEMENTOS AGRICOLAS');
insert into actividadbanxico values('3621019','FABRICACION DE HERRAMIENTAS DE METAL');
insert into actividadbanxico values('3621027','FABRICACION DE REFACCIONES Y MAQUINARIA INDUSTRIAL');
insert into actividadbanxico values('3631018','FABRICACION ENSAMBLE Y REPARACION DE MAQUINARIA Y');
insert into actividadbanxico values('3632016','FABRICACION ENSAMBLE Y REPARACION DE MAQUINARIA EQ');
insert into actividadbanxico values('3639012','FABRICACION DE MOLINOS PARA GRANOS');
insert into actividadbanxico values('3639905','USUARIOS MENORES DE FABRICACION DE MAQUINARIA Y AR');
insert into actividadbanxico values('3639913','CARTERA DE FABRICACION DE MAQUINARIA Y ARTICULOS E');
insert into actividadbanxico values('3641017','FABRICACION DE MAQUINAS CALCULADORAS REGISTRADORAS');
insert into actividadbanxico values('3641025','FAB. DE EQ. DE PROCES. ELECTR. DE DATOS');
insert into actividadbanxico values('3691012','FABRICACION DE MAQUINAS DE COSER');
insert into actividadbanxico values('3692010','FABRICACION ENSAMBLE Y REPARACION DE GRUAS MONTACA');
insert into actividadbanxico values('3693018','FABRICACION ENSAMBLE Y REPARACION DE MOTORES NO EL');
insert into actividadbanxico values('3694016','FABRICACION DE EXTINGUIDORES');
insert into actividadbanxico values('3694024','FABRICACION DE BOMBAS PARA AGUA');
insert into actividadbanxico values('3695014','FABRICACION DE VALVULAS DE METAL');
insert into actividadbanxico values('3696012','FABRICACION DE FILTROS DE METAL');
insert into actividadbanxico values('3697010','FABRICACION E INSTALACION DE EQUIPOS Y APARATOS DE');
insert into actividadbanxico values('3699016','FABRICACION DE ENGRANES DE METAL');
insert into actividadbanxico values('3699024','TALLER MECANICO DE FABRICACION Y REPARACION DE PAR');
insert into actividadbanxico values('3699032','FABRICACION DE ACCESORIOS PARA LA INDUSTRIA TEXTIL');
insert into actividadbanxico values('3711018','FABRICACION ENSAMBLE Y REPARACION DE TRANSFORMADOR');
insert into actividadbanxico values('3721017','FABRICACION DE RADIOS TOCADISCOS GRABADORAS Y TELE');
insert into actividadbanxico values('3722015','FABRICACION DE DISCOS Y CINTAS PARA GRABACIONES');
insert into actividadbanxico values('3722023','GRABACION DE DISCOS Y CINTAS');
insert into actividadbanxico values('3723013','FABRICACION DE APARATOS DE INTERCOMUNICACION');
insert into actividadbanxico values('3729011','FABRICACION DE PARTES DISPOSITIVOS Y ACCESORIOS PA');
insert into actividadbanxico values('3731016','FABRICACION DE OTROS APARATOS ELECTRICOS PARA EL H');
insert into actividadbanxico values('3731024','FABRICACION DE REFRIGERADORES Y EQUIPOS DE CALEFAC');
insert into actividadbanxico values('3791010','FABRICACION DE ACUMULADORES');
insert into actividadbanxico values('3791028','FABRICACION DE PILAS SECAS');
insert into actividadbanxico values('3792018','FABRICACION DE FOCOS');
insert into actividadbanxico values('3793016','FABRICACION DE CABLES DE METAL');
insert into actividadbanxico values('3793024','FABRICACION DE MATERIAL PARA INSTALACIONES ELECTRI');
insert into actividadbanxico values('3793032','FABRICACION DE REFACCIONES PARA APARATOS ELECTRICO');
insert into actividadbanxico values('3799014','FABRICACION DE ANUNCIOS LUMINOSOS');
insert into actividadbanxico values('3799022','FABRICACION DE CANDILES Y ARBOTANTES');
insert into actividadbanxico values('3799030','FABRICACION DE LAMPARAS ELECTRICAS');
insert into actividadbanxico values('3811016','FABRICACION Y ENSAMBLE DE AUTOMOVILES Y CAMIONES');
insert into actividadbanxico values('3812014','FABRICACION DE CARROCERIAS DE METAL');
insert into actividadbanxico values('3812022','FABRICACION DE FURGONES Y VAGONES');
insert into actividadbanxico values('3812030','FABRICACION Y ENSAMBLE DE OTROS VEHICULOS');
insert into actividadbanxico values('3813012','FABRICACION DE PISTONES BIELAS ANILLOS CIGUEÐALES');
insert into actividadbanxico values('3814010','FABRICACION DE PARTES PARA EL SISTEMA DE TRANSMISI');
insert into actividadbanxico values('3815018','FABRICACION DE MUELLES Y RESORTES PARA VEHICULOS');
insert into actividadbanxico values('3816016','FABRICACION DE PARTES PARA EL SISTEMA DE FRENOS DE');
insert into actividadbanxico values('3817014','FABRICACION DE BUJIAS');
insert into actividadbanxico values('3819010','FABRICACION DE REFACCIONES Y ACCESORIOS AUTOMOTRIC');
insert into actividadbanxico values('3821015','FABRICACION ENSAMBLE Y REPARACION DE CARROS DE FER');
insert into actividadbanxico values('3831014','FABRICACION Y REPARACION DE BUQUES Y BARCOS');
insert into actividadbanxico values('3831022','FABRICACION Y REPARACION DE OTROS VEHICULOS ACUATI');
insert into actividadbanxico values('3832012','FABRICACION ENSAMBLE Y REPARACION DE AERONAVES');
insert into actividadbanxico values('3891018','FABRICACION Y ENSAMBLE DE MOTOCICLETAS BICICLETAS');
insert into actividadbanxico values('3892016','FABRICACION DE PARTES REFACCIONES Y ACCESORIOS PAR');
insert into actividadbanxico values('3899012','FABRICACION DE CARREOLAS Y ANDADERAS');
insert into actividadbanxico values('3911014','FABRICACION Y REPARACION DE ARTICULOS DE OPTICA');
insert into actividadbanxico values('3912012','FABRICACION DE CAMARAS FOTOGRAFICAS DE CINE Y PROY');
insert into actividadbanxico values('3912020','FABRICACION DE MATERIAL FOTOGRAFICO');
insert into actividadbanxico values('3921013','FABRICACION DE RELOJES');
insert into actividadbanxico values('3931012','FABRICACION DE MEDALLAS INSIGNIAS Y PLACAS');
insert into actividadbanxico values('3932010','FABRICACION DE ARTICULOS DE JOYERIA');
insert into actividadbanxico values('3932028','ORFEBRERIA');
insert into actividadbanxico values('3932036','TALLADO DE PIEDRAS PRECIOSAS');
insert into actividadbanxico values('3933018','FABRICACION DE ARTICULOS DE QUINCALLERIA Y BISUTER');
insert into actividadbanxico values('3941011','FABRICACION DE CUERDAS PARA GUITARRA');
insert into actividadbanxico values('3941029','FABRICACION Y REPARACION DE INSTRUMENTOS MUSICALES');
insert into actividadbanxico values('3951010','FABRICACION DE APARATOS PARA GIMNASIA');
insert into actividadbanxico values('3951028','FABRICACION DE MESAS DE BILLAR');
insert into actividadbanxico values('3951036','FABRICACION DE OTROS ARTICULOS PARA DEPORTES');
insert into actividadbanxico values('3961019','FABRICACION DE OTROS INSTRUMENTOS DE MEDICION');
insert into actividadbanxico values('3961027','FABRICACION Y REPARACION DE BASCULAS Y BALANZAS');
insert into actividadbanxico values('3961035','FABRICACION Y REPARACION DE INTRUMENTOS DE FISICA');
insert into actividadbanxico values('3961043','FABRICACION Y REPARACION DE INSTRUMENTOS DE INGENI');
insert into actividadbanxico values('3961051','FABRICACION DE APARATOS OZONIZADORES');
insert into actividadbanxico values('3961069','FABRICACION DE TAXIMETROS');
insert into actividadbanxico values('3962017','FABRICACION Y REPARACION DE APARATOS ORTOPEDICOS');
insert into actividadbanxico values('3962025','FABRICACION Y REPARACION DE INSTRUMENTOS DE CIRUGI');
insert into actividadbanxico values('3991016','FABRICACION DE JUGUETES EXCEPTO LOS DE HULE Y DE P');
insert into actividadbanxico values('3992014','FABRICACION DE ARTICULOS PARA ESCRITORIO');
insert into actividadbanxico values('3992022','FABRICACION DE CANUTEROS');
insert into actividadbanxico values('3992030','FABRICACION DE CINTAS PARA MAQUINAS CALCULADORAS R');
insert into actividadbanxico values('3992048','FABRICACION DE LAPICES');
insert into actividadbanxico values('3992056','FABRICACION DE PIZARRONES');
insert into actividadbanxico values('3993012','FABRICACION DE SELLOS DE GOMA');
insert into actividadbanxico values('3993020','FABRICACION DE SELLOS PARA CARROS DE FERROCARRIL');
insert into actividadbanxico values('3994010','FABRICACION DE ARTICULOS PARA DENTISTA');
insert into actividadbanxico values('3995018','FABRICACION DE CERCOS PARA CALZADO');
insert into actividadbanxico values('3995026','FABRICACION DE HORMAS PARA CALZADO Y TACONES');
insert into actividadbanxico values('3996016','FABRICACION DE ESCOBAS');
insert into actividadbanxico values('3997014','FABRICACION DE ARMAS');
insert into actividadbanxico values('3997022','FABRICACION DE CARTUCHOS');
insert into actividadbanxico values('3997030','FABRICACION DE CASQUILLOS');
insert into actividadbanxico values('3997048','FABRICACION DE MUNICIONES PARA CAZA');
insert into actividadbanxico values('3999010','FABRICACION DE ABANICOS');
insert into actividadbanxico values('3999028','FABRICACION DE ARTICULOS DE CAREY');
insert into actividadbanxico values('3999036','FABRICACION DE ARTICULOS DE CONCHA');
insert into actividadbanxico values('3999044','FABRICACION DE BASTONES PARAGUAS Y SOMBRILLAS');
insert into actividadbanxico values('3999052','FABRICACION DE FLORES ARTIFICIALES');
insert into actividadbanxico values('3999060','FABRICACION DE OTROS ARTICULOS DE PLUMA DE AVE');
insert into actividadbanxico values('3999078','FABRICACION DE ROTULOS');
insert into actividadbanxico values('3999086','FABRICACION DE TALCO INDUSTRIAL');
insert into actividadbanxico values('3999094','FABRICACION DE TRAGALUCES Y MARQUESINAS');
insert into actividadbanxico values('3999101','FABRICACION DE PRODUCTOS MANUFACTURADOS NO CLASIFI');
insert into actividadbanxico values('3999119','AJUSTE PROGRAMA VENTA DE CARTERA FOBAPROA');
insert into actividadbanxico values('3999127','AJUSTE ESTADISTICO');
insert into actividadbanxico values('3999903','USUARIOS MENORES DE INDUSTRIA MANUFACTURERA');
insert into actividadbanxico values('3999911','CARTERA DE INDUSTRIA MANUFACTURERA DE ESTADOS ANAL');
insert into actividadbanxico values('4111019','CONSTRUCCION DE CASAS Y TECHOS DESARMABLES');
insert into actividadbanxico values('4111027','CONSTRUCCION DE INMUEBLES');
insert into actividadbanxico values('4111035','PRESTAMOS PARA LA CONSTRUCCION DE VIVIENDA, TANTO');
insert into actividadbanxico values('4111043','PRESTAMOS PARA LA CONSTRUCCION DE VIVIENDA PARA AC');
insert into actividadbanxico values('4111051','DESARROLLADORES DE VIVIENDA');
insert into actividadbanxico values('4111910','CARTERA DE VIVIENDA DE INTERES SOCIAL DE ESTADOS A');
insert into actividadbanxico values('4111928','CONSTRUCCION DE VIVIENDA TIPO MEDIO');
insert into actividadbanxico values('4111936','USUARIOS MENORES DE CONSTRUCCION DE VIVIENDA TIPO');
insert into actividadbanxico values('4111944','CONSTRUCCION DE VIVIENDA RESIDENCIAL');
insert into actividadbanxico values('4111952','USUARIOS MENORES DE CONSTRUCCION DE VIVIENDA RESID');
insert into actividadbanxico values('4112017','CONSTRUCCION DE EDIFICIOS PARA OFICINAS ESCUELAS H');
insert into actividadbanxico values('4113015','CONSTRUCCION DE EDIFICIOS INDUSTRIALES Y PARA FINE');
insert into actividadbanxico values('4121018','CONSTRUCCION DE VIAS DE COMUNICACION');
insert into actividadbanxico values('4121026','PAVIMENTACION');
insert into actividadbanxico values('4121034','URBANIZACION');
insert into actividadbanxico values('4122016','CONSTRUCCION DE PUERTOS');
insert into actividadbanxico values('4123014','CONSTRUCCION E INSTALACION DE LINEAS TELEFONICAS T');
insert into actividadbanxico values('4129012','CONSTRUCCION DE PISTAS DE ATERRIZAJE DUCTOS Y OTRA');
insert into actividadbanxico values('4191011','CONSTRUCCION DE PRESAS');
insert into actividadbanxico values('4192019','PERFORACION DE NORIAS Y POZOS PARA AGUA');
insert into actividadbanxico values('4193017','CONSTRUCCION E INSTALACION DE PLANTAS GENERADORAS');
insert into actividadbanxico values('4194015','PERFORACION DE POZOS PETROLEROS Y DE GAS');
insert into actividadbanxico values('4199015','CONSTRUCCION DE ESTADIOS MONUMENTOS Y OTRAS OBRAS');
insert into actividadbanxico values('4199908','USUARIOS MENORES DE CONSTRUCCION');
insert into actividadbanxico values('4199916','CARTERA DE CONSTRUCCION DE ESTADOS ANALITICOS');
insert into actividadbanxico values('4211017','PREMEZCLADO Y COLADO DE CONCRETO');
insert into actividadbanxico values('4212015','DEMOLICION DE INMUEBLES');
insert into actividadbanxico values('4219011','IMPERMEABILIZACION DE INMUEBLES');
insert into actividadbanxico values('4221016','TALLER DE PLOMERIA');
insert into actividadbanxico values('4222014','INSTALACIONES DEL SISTEMA ELECTRICO INCLUYE SISTEM');
insert into actividadbanxico values('4229010','INSTALACIONES DE SISTEMAS DE AIRE ACONDICIONADO Y');
insert into actividadbanxico values('4291019','SERVICIOS DE PINTADO Y TAPIZADO DE INMUEBLES');
insert into actividadbanxico values('4292017','LABRADO Y COLOCACION DE PIEDRA');
insert into actividadbanxico values('4293015','COLOCACION DE DUELAS PARQUET LAMBRINES Y OTROS TRA');
insert into actividadbanxico values('4299013','OTROS SERVICIOS DE ACABADO PRESTADOS POR SUBCONTRA');
insert into actividadbanxico values('5011010','GENERACION Y SUMINISTRO DE ENERGIA ELECTRICA');
insert into actividadbanxico values('5011903','USUARIOS MENORES DE ENERGIA ELECTRICA');
insert into actividadbanxico values('5011911','CARTERA DE ENERGIA ELECTRICA DE ESTADOS ANALITICOS');
insert into actividadbanxico values('5012018','DISTRIBUCION DE ENERGIA ELECTRICA');
insert into actividadbanxico values('5111018','CAPTACION, TRATAMIENTO, CONDUCCION Y DISTRIBUCION');
insert into actividadbanxico values('6111017','COMPRA VENTA DE SEMILLAS Y GRANOS');
insert into actividadbanxico values('6112015','COMPRA VENTA DE FRUTAS');
insert into actividadbanxico values('6112023','COMPRA VENTA DE LEGUMBRES Y HORTALIZAS');
insert into actividadbanxico values('6113013','COMPRA VENTA DE CHILE SECO Y ESPECIAS');
insert into actividadbanxico values('6114011','COMPRA VENTA DE FORRAJES EN ESTADO NATURAL');
insert into actividadbanxico values('6119011','COMPRA VENTA DE OTROS PRODUCTOS ALIMENTICIOS AGRIC');
insert into actividadbanxico values('6121016','COMPRA VENTA DE AVES EN PIE');
insert into actividadbanxico values('6121024','COMPRA VENTA DE GANADO MAYOR EN PIE');
insert into actividadbanxico values('6121032','COMPRA VENTA DE GANADO MENOR EN PIE');
insert into actividadbanxico values('6122014','COMPRA VENTA DE CARNE DE RES Y OTRAS ESPECIES DE G');
insert into actividadbanxico values('6123012','COMPRA VENTA DE VISCERAS DE GANADO CRUDAS Y SEMICR');
insert into actividadbanxico values('6124010','COMPRA VENTA DE CARNE DE AVES');
insert into actividadbanxico values('6125018','COMPRA VENTA DE HUEVO');
insert into actividadbanxico values('6126016','COMPRA VENTA DE MANTECA');
insert into actividadbanxico values('6126024','COMPRA VENTA DE MATERIAS PRIMAS ANIMALES');
insert into actividadbanxico values('6126032','COMPRA VENTA DE PESCADOS Y MARISCOS');
insert into actividadbanxico values('6131015','SALCHICHONERIA');
insert into actividadbanxico values('6131023','TIENDA DE ABARROTES Y MISCELANEA');
insert into actividadbanxico values('6132013','COMPRA VENTA DE DULCES');
insert into actividadbanxico values('6132021','COMPRA VENTA DE ESPECIAS Y ARTICULOS ALIMENTICOS D');
insert into actividadbanxico values('6132039','COMPRA VENTA DE LECHE');
insert into actividadbanxico values('6132047','COMPRA VENTA DE OTROS PRODUCTOS LACTEOS');
insert into actividadbanxico values('6132055','COMPRA VENTA DE PAN Y PASTELES');
insert into actividadbanxico values('6132063','COMPRA VENTA DE SAL');
insert into actividadbanxico values('6132071','VENTA Y DISTRIBUCION DE DESPENSAS FAMILIARES');
insert into actividadbanxico values('6132089','COMPRA VENTA DE AZUCAR');
insert into actividadbanxico values('6133011','COMPRAVENTA DE ALIMENTO PARA GANADO');
insert into actividadbanxico values('6133029','COMPRAVENTA DE ALIMENTOS PARA AVES Y OTROS ANIMALE');
insert into actividadbanxico values('6134019','COMPRA VENTA DE REFRESCOS AGUAS GASEOSAS Y AGUAS P');
insert into actividadbanxico values('6135017','COMPRA VENTA DE CERVEZA');
insert into actividadbanxico values('6136015','COMPRA VENTA DE PULQUE');
insert into actividadbanxico values('6136023','COMPRA VENTA DE VINOS Y LICORES');
insert into actividadbanxico values('6139019','COMPRA VENTA DE TABACO');
insert into actividadbanxico values('6139027','COMPRA VENTA DE TABACOS PUROS Y CIGARROS');
insert into actividadbanxico values('6211015','COMPRA VENTA DE ARTICULOS DE LENCERIA');
insert into actividadbanxico values('6211023','COMPRA VENTA DE ROPA');
insert into actividadbanxico values('6212013','COMPRA VENTA DE CALZADO');
insert into actividadbanxico values('6213011','COMPRA VENTA DE SOMBREROS');
insert into actividadbanxico values('6214019','COMPRA VENTA DE PIELES FINAS CON PELO');
insert into actividadbanxico values('6215017','COMPRA VENTA DE ARTICULOS DE MERCERIA Y SEDERIA');
insert into actividadbanxico values('6215025','COMPRAVENTA DE ARTICULOS DE BONETERIA');
insert into actividadbanxico values('6216015','COMPRA VENTA DE CASIMIRES');
insert into actividadbanxico values('6216023','COMPRA VENTA DE OTROS PRODUCTOS TEXTILES');
insert into actividadbanxico values('6216031','COMPRA VENTA DE TELAS');
insert into actividadbanxico values('6221014','COMPRA VENTA DE ARTICULOS PARA DEPORTE');
insert into actividadbanxico values('6222012','COMPRA VENTA DE ARTICULOS DE OPTICA');
insert into actividadbanxico values('6223010','COMPRA VENTA DE JUGUETES');
insert into actividadbanxico values('6224018','COMPRA VENTA DE INSTRUMENTOS Y ARTICULOS MUSICALES');
insert into actividadbanxico values('6225016','COMPRA VENTA DE ARTICULOS DE PLATA');
insert into actividadbanxico values('6225024','COMPRA VENTA DE OTRAS JOYAS');
insert into actividadbanxico values('6225032','COMPRA VENTA DE RELOJES');
insert into actividadbanxico values('6226014','COMPRA VENTA DE ARTICULOS DE TALABARTERIA');
insert into actividadbanxico values('6226022','COMPRA VENTA DE OTROS ARTICULOS DE PIEL');
insert into actividadbanxico values('6226030','COMPRA VENTA DE SILLAS DE MONTAR');
insert into actividadbanxico values('6227012','COMPRA VENTA DE LIBROS');
insert into actividadbanxico values('6228010','DISTRIBUCION Y COMPRAVENTA DE PERIODICOS Y REVISTA');
insert into actividadbanxico values('6229018','COMPRA VENTA DE ARTICULOS FOTOGRAFICOS Y CINEMATOG');
insert into actividadbanxico values('6231013','COMPRA VENTA DE MEDICINAS');
insert into actividadbanxico values('6231021','COMPRA VENTA DE PERFUMES');
insert into actividadbanxico values('6232011','DISTRIBUCION DE OTROS PRODUCTOS QUIMICOS-FARMACEUT');
insert into actividadbanxico values('6233019','COMPRA VENTA DE PAPELERIA Y ARTICULOS DE ESCRITORI');
insert into actividadbanxico values('6239017','COMPRA VENTA DE PARAGUAS SOMBRILLAS ROPA USADA Y O');
insert into actividadbanxico values('6311013','COMPRA VENTA DE REFRIGERADORES LAVADORAS Y ESTUFAS');
insert into actividadbanxico values('6311021','COMPRA VENTA DE TELEVISORES CONSOLAS RADIOS MODULA');
insert into actividadbanxico values('6311039','COMPRAVENTA DE OTROS APARATOS ELECTRICOS Y ELECTRO');
insert into actividadbanxico values('6312011','COMPRA VENTA DE MUEBLES');
insert into actividadbanxico values('6313019','COMPRA VENTA DE MAQUINAS DE COSER Y TEJEDORAS');
insert into actividadbanxico values('6314017','COMPRA VENTA DE REFACCIONES Y ACCESORIOS DE MAQUIN');
insert into actividadbanxico values('6321012','COMPRA VENTA DE ARTICULOS DE CRISTAL LOZA Y PORCEL');
insert into actividadbanxico values('6322010','COMPRA VENTA DE ARTICULOS PARA DECORACION');
insert into actividadbanxico values('6322028','COMPRA VENTA DE TAPETES Y ALFOMBRAS');
insert into actividadbanxico values('6323018','COMPRA VENTA DE DISCOS Y CASSETTES');
insert into actividadbanxico values('6324016','COMPRA VENTA DE ARTICULOS RELIGIOSOS');
insert into actividadbanxico values('6325014','COMPRA VENTA DE ANTIGUEDADES');
insert into actividadbanxico values('6325022','COMPRA VENTA DE ARTICULOS DE YUTE Y HENEQUEN');
insert into actividadbanxico values('6325030','COMPRA VENTA DE ARTICULOS PARA REGALO');
insert into actividadbanxico values('6325048','COMPRA VENTA DE ARTICULOS REGIONALES CURIOSIDADES');
insert into actividadbanxico values('6326012','COMPRA VENTA DE FLORES Y ADORNOS FLORALES ARTIFICI');
insert into actividadbanxico values('6326020','COMPRA VENTA DE FLORES Y ADORNOS FLORALES NATURALE');
insert into actividadbanxico values('6329016','COMPRA VENTA DE OTROS ARTICULOS PARA EL HOGAR');
insert into actividadbanxico values('6411011','TIENDA DE AUTOSERVICIO');
insert into actividadbanxico values('6412019','TIENDAS DE DEPARTAMENTOS ESPECIALIZADOS EXCEPTO DE');
insert into actividadbanxico values('6419015','COMPRA VENTA DE OTROS APARATOS ELECTRICOS');
insert into actividadbanxico values('6419023','COMPRA VENTA DE REFACCIONES PARA APARATOS ELECTRIC');
insert into actividadbanxico values('6511019','COMPRA VENTA DE FLUIDOS Y GASES');
insert into actividadbanxico values('6512017','COMPRA VENTA DE GAS PARA USO DOMESTICO O COMERCIAL');
insert into actividadbanxico values('6513015','COMPRA VENTA DE GASOLINA Y DIESEL');
insert into actividadbanxico values('6514013','COMPRA VENTA DE PETROLEO COMBUSTIBLE');
insert into actividadbanxico values('6515011','COMPRAVENTA DE LUBRICANTES');
insert into actividadbanxico values('6519013','COMPRA VENTA DE CARBON Y OTROS COMBUSTIBLES');
insert into actividadbanxico values('6611017','COMPRA VENTA DE ALGODON');
insert into actividadbanxico values('6612015','COMPRA VENTA DE SEMILLAS PARA SIEMBRA');
insert into actividadbanxico values('6613013','COMPRA VENTA DE CUEROS Y PIELES SIN CURTIR');
insert into actividadbanxico values('6619011','COMPRA VENTA DE HENEQUEN E IXTLE');
insert into actividadbanxico values('6619029','COMPRA VENTA DE LANA');
insert into actividadbanxico values('6619037','COMPRA VENTA DE OTRAS MATERIAS PRIMAS VEGETALES');
insert into actividadbanxico values('6619045','COMPRA VENTA DE OTRAS FIBRAS COMERCIALES');
insert into actividadbanxico values('6619053','COMPRA VENTA DE OTRAS MATERIAS PRIMAS DE ORIGEN AN');
insert into actividadbanxico values('6621016','COMPRA VENTA DE CEMENTO CAL YESO Y OTROS PRODUCTOS');
insert into actividadbanxico values('6622014','COMPRA VENTA DE FIERRO LAMINADO Y EN LINGOTES');
insert into actividadbanxico values('6622022','COMPRAVENTA DE ARTICULOS DE FERRETERIA');
insert into actividadbanxico values('6623012','COMPRA VENTA DE COLORANTES PARA LA INDUSTRIA');
insert into actividadbanxico values('6623020','COMPRA VENTA DE PINTURAS BARNICES Y BROCHAS');
insert into actividadbanxico values('6624010','COMPRA VENTA DE MADERA');
insert into actividadbanxico values('6625018','COMPRA VENTA DE VIDRIOS CRISTALES Y EMPLOMADOS');
insert into actividadbanxico values('6626016','COMPRA VENTA DE ANILINAS');
insert into actividadbanxico values('6626024','COMPRA VENTA DE ARTICULOS DE TLAPALERIA');
insert into actividadbanxico values('6626032','COMPRA VENTA DE COSTALES Y BOLSAS');
insert into actividadbanxico values('6627014','COMPRA DE ARTICULOS SANITARIOS');
insert into actividadbanxico values('6628012','COMPRA VENTA DE MATERIAL PARA INSTALACIONES ELECTR');
insert into actividadbanxico values('6629010','COMPRA VENTA DE MATERIALES PARA CONSTRUCCION');
insert into actividadbanxico values('6629028','COMPRA VENTA DE TAPICES');
insert into actividadbanxico values('6691019','COMPRA VENTA DE FERTILIZANTES Y PLAGUICIDAS');
insert into actividadbanxico values('6692017','COMPRA VENTA DE ARTICULOS DE PELETERIA');
insert into actividadbanxico values('6693015','COMPRA VENTA DE DESPERDICIOS DE PAPEL');
insert into actividadbanxico values('6694013','COMPRA VENTA DE FIERRO USADO');
insert into actividadbanxico values('6695011','COMPRAVENTA DE SUBSTANCIAS QUIMICAS PARA LA INDUST');
insert into actividadbanxico values('6699013','COMPRA VENTA DE CERAS Y PARAFINAS');
insert into actividadbanxico values('6699021','COMPRA VENTA DE DESPERDICIOS INDUSTRIALES');
insert into actividadbanxico values('6699039','COMPRA VENTA DE MATERIAS PRIMAS DE ORIGEN MINERAL');
insert into actividadbanxico values('6699047','COMPRAVENTA DE OTROS METALES Y MINERALES LAMINADOS');
insert into actividadbanxico values('6711015','COMPRA VENTA DE MAQUINARIA EQUIPO E IMPLEMENTOS PA');
insert into actividadbanxico values('6712013','COMPRA VENTA DE ARTICULOS PARA LA EXPLOTACION DE M');
insert into actividadbanxico values('6713011','COMPRAVENTA MAQ, EQ, IMPLEM Y HERRAM PARA TRABAJAR');
insert into actividadbanxico values('6714019','COMPRA VENTA DE MAQUINARIA NUEVA');
insert into actividadbanxico values('6714027','COMPRA VENTA DE MAQUINARIA USADA');
insert into actividadbanxico values('6714035','COMPRA VENTA DE EQUIPO DE TRABAJO Y PROTECCION IND');
insert into actividadbanxico values('6719019','COMPRA VENTA DE REFACCIONES PARA MAQUINARIA');
insert into actividadbanxico values('6721014','COMPRA VENTA DE MAQUINAS DE ESCRIBIR');
insert into actividadbanxico values('6721022','COMPRA VENTA DE MUEBLES Y ARTICULOS PARA OFICINA');
insert into actividadbanxico values('6721036','COMPRA VENTA EQUIPO DE PROCE. ELECTRONICO DE DATOS');
insert into actividadbanxico values('6722012','COMPRA VENTA DE EQUIPO Y MOBILIARIO PARA HOTELES R');
insert into actividadbanxico values('6729018','COMPRA VENTA DE EQUIPOS DE REFRIGERACION COMERCIAL');
insert into actividadbanxico values('6729026','COMPRA VENTA DE ACCESORIOS PARA MUEBLES');
insert into actividadbanxico values('6729034','COMPRA VENTA DE EQUIPO CONTRA INCENDIO');
insert into actividadbanxico values('6731013','COMPRA VENTA DE BASCULAS BALANZAS Y APARATOS SIMIL');
insert into actividadbanxico values('6732011','COMPRA VENTA DE ARTICULOS MEDICOS');
insert into actividadbanxico values('6732029','COMPRA VENTA DE ARTICULOS Y APARATOS ORTOPEDICOS');
insert into actividadbanxico values('6732037','COMPRA VENTA DE MUEBLES PARA CONSULTORIOS Y SANATO');
insert into actividadbanxico values('6732045','COMPRAVENTA DE EQUIPOS QUIMICOS Y PARA LABORATORIO');
insert into actividadbanxico values('6739017','COMPRA VENTA DE APARATOS CIENTIFICOS Y DE PRECISIO');
insert into actividadbanxico values('6811013','COMPRA VENTA DE AUTOMOVILES Y CAMIONES NUEVOS');
insert into actividadbanxico values('6812011','COMPRA VENTA DE AUTOMOVILES Y CAMIONES USADOS');
insert into actividadbanxico values('6813019','COMPRA VENTA DE BICICLETAS Y SUS ACCESORIOS');
insert into actividadbanxico values('6813027','COMPRA VENTA DE MOTOCICLETAS Y SUS ACCESORIOS');
insert into actividadbanxico values('6814017','COMPRA VENTA DE LLANTAS');
insert into actividadbanxico values('6815015','COMPRAVENTA DE REFACCIONES Y ACCESORIOS NUEVOS PAR');
insert into actividadbanxico values('6816013','COMPRA VENTA DE REFACCIONES Y ACCESORIOS USADOS PA');
insert into actividadbanxico values('6819017','COMPRA VENTA DE PARTES Y REFACCIONES PARA VEHICULO');
insert into actividadbanxico values('6819025','COMPRA VENTA DE VEHICULOS ACUATICOS Y SUS REFACCIO');
insert into actividadbanxico values('6819033','COMPRAVENTA DE VEHICULOS AEREOS');
insert into actividadbanxico values('6911011','PRESTAMOS PARA LA ADQUISISION DE VIVIENDA PARA ACR');
insert into actividadbanxico values('6911029','COMPRA DE CASA HABITACION');
insert into actividadbanxico values('6911037','PRESTAMOS PARA LA ADQUISICION DE VIVIENDA TANTO DE');
insert into actividadbanxico values('6911045','COMPRA VENTA DE CASAS Y OTROS INMUEBLES');
insert into actividadbanxico values('6911053','COMPRA VENTA DE TERRENOS');
insert into actividadbanxico values('6911061','ACTUALIZACION MENSUAL DEL SALDO OPERACIONES DE CRE');
insert into actividadbanxico values('6911079','ADQUISICION DE VIVIENDA TIPO MEDIO');
insert into actividadbanxico values('6911087','USUARIOS MENORES DE ADQUISICION DE VIVIENDA TIPO M');
insert into actividadbanxico values('6911095','ADQUISICION DE VIVIENDA RESIDENCIAL');
insert into actividadbanxico values('6911102','USUARIOS MENORES DE ADQUISICION DE VIVIENDA RESIDE');
insert into actividadbanxico values('6991013','COMPRA VENTA DE ARMAS DE FUEGO');
insert into actividadbanxico values('6992011','AGENCIAS DE RIFAS Y SORTEOS (QUINIELAS Y LOTERIA)');
insert into actividadbanxico values('6993019','COMPRAVENTA DE PRODUCTOS VETERINARIOS Y OTROS ARTI');
insert into actividadbanxico values('6999017','COMPRA VENTA DE DIAMANTES');
insert into actividadbanxico values('6999025','COMPRA VENTA DE EQUIPOS Y APARATOS DE AIRE ACONDIC');
insert into actividadbanxico values('6999033','COMPRAVENTA DE JARCIERIA REATAS CANASTAS Y ARTICUL');
insert into actividadbanxico values('6999041','COMPRA VENTA DE OTROS ARTICULOS DE PLASTICO');
insert into actividadbanxico values('6999059','USUARIOS MENORES POR OPERACIONES DE REPORTO');
insert into actividadbanxico values('6999067','COMPRAVENTA DE OTROS PRODUCTOS DE HULE');
insert into actividadbanxico values('6999075','COMPRA VENTA DE VELAS Y VELADORAS');
insert into actividadbanxico values('6999083','CREDITOS PERSONALES AL CONSUMO');
insert into actividadbanxico values('6999091','PRESTAMOS AL PERSONAL DE LA INSTITUCION');
insert into actividadbanxico values('6999108','COMPRA VENTA DE ARTICULOS NO CLASIFICADOS EN OTRA');
insert into actividadbanxico values('6999116','USUARIOS DE TARJETA DE CREDITO');
insert into actividadbanxico values('6999124','CREDITOS PARA ADQUISICION DE BIENES DE CONSUMO DUR');
insert into actividadbanxico values('6999900','USUARIOS MENORES DE COMERCIO');
insert into actividadbanxico values('6999991','CARTERA DE COMERCIO DE ESTADOS ANALITICOS');
insert into actividadbanxico values('6999992','CENTROS CAMBIARIOS');
insert into actividadbanxico values('7111016','TRANSPORTE EN AUTOBUS URBANO Y SUBURBANO DE PASAJE');
insert into actividadbanxico values('7112014','TRANSPORTE EN AUTOBUS FORANEO DE PASAJEROS');
insert into actividadbanxico values('7113012','TRANSPORTE EN AUTOMOVIL DE RULETEO');
insert into actividadbanxico values('7114010','TRANSPORTE EN AUTOMOVILES DE SITIO Y TURISMO');
insert into actividadbanxico values('7115018','TRANSPORTE EN AUTOMOVIL DE RUTA FIJA');
insert into actividadbanxico values('7119010','AUTOTRANSPORTE ESCOLAR TURISTICO EN AUTOBUS Y OTRO');
insert into actividadbanxico values('7121015','AUTOTRANSPORTE DE MATERIALES DE CONSTRUCCION');
insert into actividadbanxico values('7122013','AGENCIA DE MUDANZAS');
insert into actividadbanxico values('7123011','AUTOTRANSPORTE DE CARGA DE PRODUCTOS ESPECIFICOS');
insert into actividadbanxico values('7129019','TRANSPORTE DE CARGA FORANEA');
insert into actividadbanxico values('7129902','USUARIOS MENORES DE TRANSPORTES');
insert into actividadbanxico values('7129910','CARTERA DE TRANSPORTES DE ESTADOS ANALITICOS');
insert into actividadbanxico values('7131014','FERROCARRILES');
insert into actividadbanxico values('7132012','TRANVIAS Y TROLEBUSES');
insert into actividadbanxico values('7133010','TRANSPORTE EN FERROCARRIL URBANO (METRO)');
insert into actividadbanxico values('7191018','TRANSPORTE POR DUCTOS');
insert into actividadbanxico values('7211014','AGENCIA DE VAPORES Y BUQUES');
insert into actividadbanxico values('7212012','TRANSPORTES MARITIMOS DE CABOTAJE');
insert into actividadbanxico values('7291016','TRANSPORTE FLUVIAL Y LACUSTRE');
insert into actividadbanxico values('7299010','CARGA Y ESTIBA PORTUARIA');
insert into actividadbanxico values('7311012','TRANSPORTACION AEREA DE PASAJEROS');
insert into actividadbanxico values('7312010','SERVICIOS RELACIONADOS CON EL TRANSPORTE EN AERONA');
insert into actividadbanxico values('7411010','ADMINISTRACION DE CAMINOS PUENTES Y SERVICIOS AUXI');
insert into actividadbanxico values('7412018','AEROPUERTO CIVIL');
insert into actividadbanxico values('7413016','ADMINISTRACION DE PUERTOS MARITIMOS LACUSTRES Y FL');
insert into actividadbanxico values('7414014','ADMINISTRACION DE CENTRALES CAMIONERAS Y SERVICIOS');
insert into actividadbanxico values('7511018','SERVICIOS DE ALMACENAMIENTO Y REFRIGERACION');
insert into actividadbanxico values('7512016','AGENCIA DE TURISMO');
insert into actividadbanxico values('7513014','AGENCIA ADUANAL');
insert into actividadbanxico values('7514012','SERVICIOS DE BASCULA Y DE GRUA PARA VEHICULOS');
insert into actividadbanxico values('7519012','AGENCIA DE FERROCARRIL');
insert into actividadbanxico values('7519020','ALQUILER DE LANCHAS Y VELEROS');
insert into actividadbanxico values('7519038','RENTA DE VEHICULOS AEREOS');
insert into actividadbanxico values('7611016','EMPRESA DE TELEFONOS');
insert into actividadbanxico values('7612014','EMPRESA DE TELEGRAFOS');
insert into actividadbanxico values('7613012','OTROS SERVS. DE TELECOMUNICACIONES (EXCEPTO RADIO.');
insert into actividadbanxico values('7613905','USUARIOS MENORES DE COMUNICACIONES');
insert into actividadbanxico values('7613913','CARTERA DE COMUNICACIONES DE ESTADOS ANALITICOS');
insert into actividadbanxico values('7614010','SERVICIOS POSTALES');
insert into actividadbanxico values('8113011','SERVICIOS DE LA BANCA NACIONAL');
insert into actividadbanxico values('8113029','SERVICIOS DE LA BANCA NACIONAL POR OPERACIONES DE');
insert into actividadbanxico values('8113128','USUARIOS MENORES DE LA BANCA DE DESARROLLO');
insert into actividadbanxico values('8114019','SERVICIOS DE FONDOS Y FIDEICOMISOS DE FOMENTO ECON');
insert into actividadbanxico values('8123010','SERVICIOS DE LA BANCA PRIVADA Y MIXTA MULTIPLE');
insert into actividadbanxico values('8123028','SERVICIOS DE LA BANCA PRIVADA ESPECIALIZADA');
insert into actividadbanxico values('8123036','SERVICIOS DE LA BANCA PRIVADA Y MIXTA MULTIPLE POR');
insert into actividadbanxico values('8123044','SERVICIOS DE LA BANCA PRIVADA ESPECIALIZADA POR OP');
insert into actividadbanxico values('8123052','SOCIEDADES DE AHORRO Y PRESTAMO');
insert into actividadbanxico values('8123060','SOCIEDADES DE AHORRO Y CREDITO POPULAR');
insert into actividadbanxico values('8123078','SOCIEDADES FINANCIERAS DE OBJETO LIMITADO');
insert into actividadbanxico values('8123086','SOCIEDADES FINANCIERAS DE OBJETO MíLTIPLE REGULADA');
insert into actividadbanxico values('8123094','SOCIEDADES FINANCIERAS DE OBJETO MíLTIPLE NO REGUL');
insert into actividadbanxico values('8123143','USUARIOS MENORES DE LA BANCA COMERCIAL');
insert into actividadbanxico values('8123903','USUARIOS MENORES DE SERVICIOS BANCARIOS');
insert into actividadbanxico values('8123911','CARTERA DE SERVICIOS BANCARIOS DE ESTADOS ANALITIC');
insert into actividadbanxico values('8131013','ALMACENES DE DEPOSITO NACIONALES');
insert into actividadbanxico values('8131021','ALMACENES DE DEPOSITO PRIVADOS');
insert into actividadbanxico values('8132011','UNIONES DE CREDITO NACIONALES');
insert into actividadbanxico values('8132029','UNIONES DE CREDITO PRIVADAS');
insert into actividadbanxico values('8133019','COMPAÑIAS DE FIANZAS NACIONALES');
insert into actividadbanxico values('8133027','COMPAÐIAS DE FIANZAS PRIVADAS');
insert into actividadbanxico values('8133035','AJ. INT. FINANCIEROS NO BANCARIOS UDIS');
insert into actividadbanxico values('8141012','BOLSA DE VALORES');
insert into actividadbanxico values('8142010','SOCIEDADES DE INVERSION');
insert into actividadbanxico values('8151011','COMPAÐIAS DE SEGUROS NACIONALES');
insert into actividadbanxico values('8151029','COMPAÐIAS DE SEGUROS PRIVADAS');
insert into actividadbanxico values('8211013','INVERSIONISTA');
insert into actividadbanxico values('8211021','AGENTE DE BOLSA');
insert into actividadbanxico values('8211039','BOLSA DE VALORES');
insert into actividadbanxico values('8211047','CASAS DE BOLSA PRIVADAS');
insert into actividadbanxico values('8219017','AGENTE DE SEGUROS');
insert into actividadbanxico values('8219025','CASA DE CAMBIO');
insert into actividadbanxico values('8219033','CORRESPONSAL BANCARIO');
insert into actividadbanxico values('8219041','CAJA DE AHORROS');
insert into actividadbanxico values('8219059','MONTEPIO');
insert into actividadbanxico values('8219067','PRESTAMISTA');
insert into actividadbanxico values('8219075','FACTORING');
insert into actividadbanxico values('8219083','EMPRESAS CONTROLADORAS FINANCIERAS');
insert into actividadbanxico values('8219091','USUARIOS MENORES DE OTROS INTERMEDIARIOS FINANCIER');
insert into actividadbanxico values('8219108','USUARIOS MENORES DE OTROS INTERMEDIARIOS FINANCIER');
insert into actividadbanxico values('8219114','ADMINISTRADORAS DE TARJETAS DE CREDITO');
insert into actividadbanxico values('8219122','EMPRESAS DE AUTOFINANCIAMIENTO AUTOMOTRIZ');
insert into actividadbanxico values('8219130','EMPRESAS DE AUTOFINANCIAMIENTO RESIDENCIAL');
insert into actividadbanxico values('8220014','FOBAPROA-IPAB');
insert into actividadbanxico values('8311011','ALQUILER DE TERRENOS, LOCALES Y EDIFICIOS NO RESID');
insert into actividadbanxico values('8312019','ARRENDAMIENTO DE INMUEBLES RESIDENCIALES');
insert into actividadbanxico values('8313017','SERVICIO DE CORREDORES DE BIENES RAICES');
insert into actividadbanxico values('8314015','ADMINISTRACION DE INMUEBLES');
insert into actividadbanxico values('8411019','SERVICIOS DE NOTARIAS PUBLICAS');
insert into actividadbanxico values('8412017','SERVICIOS DE BUFETES JURIDICOS');
insert into actividadbanxico values('8413015','SERVICIOS DE CONTADURIA Y AUDITORIA INCLUSO TENED');
insert into actividadbanxico values('8414013','SERVICIOS DE ASESORIA Y ESTUDIOS TECNICOS DE ARQUI');
insert into actividadbanxico values('8415011','DESPACHO DE OTROS PROFESIONISTAS');
insert into actividadbanxico values('8419013','SERVICIO DE INVESTIGACION DE MERCADO, SOLVENCIA FI');
insert into actividadbanxico values('8421018','SERVICIOS DE ANALISIS DE SISTEMAS Y PROCESAMIENTO');
insert into actividadbanxico values('8422016','AGENCIA DE PUBLICIDAD');
insert into actividadbanxico values('8423014','AGENCIA NOTICIOSA');
insert into actividadbanxico values('8424012','SERVICIOS ADMINISTRATIVOS DE TRAMITE Y COBRANZA IN');
insert into actividadbanxico values('8425010','SERVICIOS DE COPIAS FOTOSTATICAS XEROGRAFICAS Y SI');
insert into actividadbanxico values('8426018','COMISIONISTA');
insert into actividadbanxico values('8426026','REPRESENTACION DE ARTISTAS');
insert into actividadbanxico values('8426034','REPRESENTANTE CASAS EXTRANJERAS');
insert into actividadbanxico values('8426042','REPRESENTANTE CASAS NACIONALES');
insert into actividadbanxico values('8427016','SERVICIOS DE INSTALACION Y MANTENIMIENTO DE MAQUIN');
insert into actividadbanxico values('8428014','SERVICIOS DE AGENCIAS DE COLOCACION Y SELECCION DE');
insert into actividadbanxico values('8429012','PRESTACION DE OTROS SERVICIOS TECNICOS');
insert into actividadbanxico values('8429020','EMPRESAS CONTROLADORAS NO FINANCIERAS');
insert into actividadbanxico values('8429038','EMPRESAS DE SEGURIDAD PRIVADA');
insert into actividadbanxico values('8429046','EMPRESAS TRANSPORTADORAS DE VALORES');
insert into actividadbanxico values('8511017','ARRENDAMIENTO DE MAQUINARIA');
insert into actividadbanxico values('8511025','ARRENDADORAS FINANCIERAS NACIONALES');
insert into actividadbanxico values('8511033','ARRENDADORAS FINANCIERAS PRIVADAS');
insert into actividadbanxico values('8512015','ARRENDAMIENTO DE EQUIPO PARA PROCESAMIENTO ELECTRO');
insert into actividadbanxico values('8519011','ALQUILER DE MOBILIARIO Y EQUIPO PARA COMERCIOS, SE');
insert into actividadbanxico values('8521016','SALON DE FIESTAS');
insert into actividadbanxico values('8522014','ALQUILER DE SILLAS Y VAJILLAS PARA BANQUETES');
insert into actividadbanxico values('8523012','ALQUILER DE EQUIPOS ELECTRONICOS');
insert into actividadbanxico values('8524010','ALQUILER O RENTA DE AUTOMOVILES SIN CHOFER');
insert into actividadbanxico values('8529010','ALQUILER DE ROPA');
insert into actividadbanxico values('8611015','HOTEL');
insert into actividadbanxico values('8612013','SERVICIOS DE ALOJAMIENTO EN MOTELES');
insert into actividadbanxico values('8613011','CAMPOS DE TURISMO');
insert into actividadbanxico values('8619019','CASA DE HUESPEDES');
insert into actividadbanxico values('8711013','CAFETERIA');
insert into actividadbanxico values('8711021','RESTAURANTE');
insert into actividadbanxico values('8712011','SERVICIOS DE ALIMENTOS EN LONCHERIAS TAQUERIAS Y T');
insert into actividadbanxico values('8713019','SERVICIOS EN OSTIONERIAS Y PREPARACION DE OTROS MA');
insert into actividadbanxico values('8714017','NEVERIA Y REFRESQUERIA');
insert into actividadbanxico values('8719017','SERVICIOS EN MERENDEROS CENADURIAS Y PREPARACION D');
insert into actividadbanxico values('8721012','BARES Y CANTINAS');
insert into actividadbanxico values('8722010','CERVECERIA');
insert into actividadbanxico values('8723018','SERVICIOS EN PULQUERIAS');
insert into actividadbanxico values('8723026','USUARIOS MENORES DE TURISMO');
insert into actividadbanxico values('8811011','SERVICIOS EN BALNEARIOS Y ALBERCAS');
insert into actividadbanxico values('8812019','SALON DE BILLAR');
insert into actividadbanxico values('8812027','SALON DE BOLICHE');
insert into actividadbanxico values('8813017','CLUB SOCIAL');
insert into actividadbanxico values('8814015','CENTRO DEPORTIVO');
insert into actividadbanxico values('8819015','SERVICIOS Y EXPLOTACION DE PLAYAS Y PARQUES DE DES');
insert into actividadbanxico values('8821010','ESTUDIOS CINEMATOGRAFICOS');
insert into actividadbanxico values('8821028','GRABACION DE SONIDO EN PELICULAS');
insert into actividadbanxico values('8821036','LABORATORIOS CINEMATOGRAFICOS');
insert into actividadbanxico values('8821044','PRODUCCION DE PELICULAS');
insert into actividadbanxico values('8822018','DISTRIBUCION Y ALQUILER DE PELICULAS');
insert into actividadbanxico values('8823016','SALA DE CINE');
insert into actividadbanxico values('8824014','RADIODIFUSORA');
insert into actividadbanxico values('8825012','TELEDIFUSORA');
insert into actividadbanxico values('8826010','TEATRO');
insert into actividadbanxico values('8827018','ACTIVIDADES DE CLUBES DEPORTIVOS PROFESIONALES');
insert into actividadbanxico values('8829014','ESTADIOS Y ARENAS');
insert into actividadbanxico values('8829022','HIPODROMO');
insert into actividadbanxico values('8829030','PLAZA DE TOROS');
insert into actividadbanxico values('8829048','PROMOCION DE ESPECTACULOS DEPORTIVOS');
insert into actividadbanxico values('8829056','PROMOCION DE ESPECTACULOS TAURINOS');
insert into actividadbanxico values('8831019','CENTRO NOCTURNO');
insert into actividadbanxico values('8832017','GALERIAS DE ARTES GRAFICAS Y MUSEOS');
insert into actividadbanxico values('8833015','FEDERACIONES Y ASOCIACIONES DEPORTIVAS Y OTRAS CON');
insert into actividadbanxico values('8839013','JUEGOS DE FERIA');
insert into actividadbanxico values('8839906','USUARIOS MENORES DE SERVICIOS DE ESPARCIMIENTO');
insert into actividadbanxico values('8839914','CARTERA DE SERVICIOS DE ESPARCIMIENTO DE ESTADOS A');
insert into actividadbanxico values('8911019','TALLER DE REPARACION GENERAL DE AUTOMOVILES Y CAMI');
insert into actividadbanxico values('8912017','SERVICIOS DE REPARACION DE MOTOCICLETAS Y BICICLET');
insert into actividadbanxico values('8913015','SERVICIOS DE REPARACION ESPECIALIZADO EN PARTES DE');
insert into actividadbanxico values('8914013','SERVICIOS DE REPARACION DE CARROCERIAS PINTURA TAP');
insert into actividadbanxico values('8915011','SERVICIOS DE LAVADO Y LUBRICACION DE AUTOMOVILES');
insert into actividadbanxico values('8916019','ESTACIONAMIENTO PRIVADO PARA VEHICULOS');
insert into actividadbanxico values('8916027','ESTACIONAMIENTO PUBLICO PARA VEHICULOS');
insert into actividadbanxico values('8919013','SERVICIO DE REPARACION DE VEHICULOS DE TRACCION AN');
insert into actividadbanxico values('8921018','TALLER DE REPARACION DE CALZADO');
insert into actividadbanxico values('8922016','TALLER DE REPARACION DE APARATOS ELECTRICOS Y ELEC');
insert into actividadbanxico values('8922024','TALLER DE REPARACION DE ARTICULOS ELECTRICOS Y ELE');
insert into actividadbanxico values('8923014','SERVICIOS DE REPARACION DE RELOJES Y JOYAS');
insert into actividadbanxico values('8924012','TALLER DE TAPICERIA');
insert into actividadbanxico values('8929012','TALLER DE REPARACION DE PARAGUAS Y SOMBRILLAS');
insert into actividadbanxico values('8929020','TALLER DE REPARACION DE ROPA Y MEDIAS');
insert into actividadbanxico values('8929038','TALLER DE REPARACION DE SOMBREROS');
insert into actividadbanxico values('8931017','BA/OS');
insert into actividadbanxico values('8932015','BARBERIA Y PELUQUERIA');
insert into actividadbanxico values('8933013','SALON DE BELLEZA');
insert into actividadbanxico values('8934011','LAVANDERIA');
insert into actividadbanxico values('8934029','TINTORERIA Y PLANCHADURIA');
insert into actividadbanxico values('8935019','EMPRESA DE SERVICIO DE LIMPIEZA');
insert into actividadbanxico values('8936017','SERVICIOS DE FUMIGACION, DESINFECCION Y CONTROL DE');
insert into actividadbanxico values('8939011','SERVICIOS DE BOLERIAS, MASAJISTAS, SANITARIOS PUBL');
insert into actividadbanxico values('8941016','ESTUDIO FOTOGRAFICO');
insert into actividadbanxico values('8942014','DECORACION EN GENERAL');
insert into actividadbanxico values('8943012','AGENCIA DE INHUMACIONES');
insert into actividadbanxico values('8944010','PANTEON');
insert into actividadbanxico values('8944028','USUARIOS MENORES DE SERVICIOS PROFESIONALES Y TECN');
insert into actividadbanxico values('8944098','EMPLEADO PRIVADO');
insert into actividadbanxico values('8949010','TAXIDERMISTA');
insert into actividadbanxico values('8949888','USUARIOS MENORES DE OTRAS ACTIVIDADES');
insert into actividadbanxico values('8949896','CARTERA DE OTRAS ACTIVIDADES DE ESTADOS ANALITICOS');
insert into actividadbanxico values('8949903','USUARIOS MENORES DE SERVICIOS');
insert into actividadbanxico values('8949911','CARTERA DE SERVICIOS DE ESTADOS ANALITICOS');
insert into actividadbanxico values('8991011','QUEHACERES DEL HOGAR');
insert into actividadbanxico values('9112012','SERVICIOS DE ENSEÐANZA PREPRIMARIA Y PRIMARIA');
insert into actividadbanxico values('9113010','SERVICIOS DE ENSEÐANZA SECUNDARIA');
insert into actividadbanxico values('9115016','ESTABLECIMIENTOS PUBLICOS DE INSTRUCCION, EDUCACIO');
insert into actividadbanxico values('9119018','ESTABLECIMIENTOS PRIVADOS DE INSTRUCCION EDUCACION');
insert into actividadbanxico values('9121013','SERVICIOS DE ENSEÐANZA COMERCIAL Y DE IDIOMA');
insert into actividadbanxico values('9122011','SERVICIOS DE CAPACITACION TECNICA DE OFICIOS Y ART');
insert into actividadbanxico values('9129017','SERVICIOS DE ENSEÐANZA DE MUSICA DANZA Y OTRAS ART');
insert into actividadbanxico values('9191016','SERVICIOS DE INVESTIGACION CIENTIFICA');
insert into actividadbanxico values('9199010','SERVICIOS DE BIBLIOTECAS MUSEOS JARDINES BOTANICOS');
insert into actividadbanxico values('9211012','HOSPITALES, SANATORIOS, CLINICAS Y MATERNIDADES');
insert into actividadbanxico values('9212010','SERVICIOS MEDICO GENERAL Y ESPECIALIZADO EN CONSUL');
insert into actividadbanxico values('9213018','SERVICIOS DE CONSULTORIOS Y CLINICAS DENTALES');
insert into actividadbanxico values('9214016','LABORATORIOS DE ANALISIS CLINICOS');
insert into actividadbanxico values('9215014','SERVICIOS DE LABORATORIOS DE RADIOLOGIA Y RADIOSCO');
insert into actividadbanxico values('9219016','SERVICIOS DE FISIOTERAPIA, BANCOS DE SANGRE Y OTRO');
insert into actividadbanxico values('9221011','CENTRO DE BENEFICENCIA');
insert into actividadbanxico values('9231010','SERVICIOS VETERINARIOS EN CLINICAS Y CONSULTORIOS,');
insert into actividadbanxico values('9231028','USUARIOS MENORES DE SERVICIOS MEDICOS');
insert into actividadbanxico values('9311010','ASOCIACIONES Y CONFEDERACIONES');
insert into actividadbanxico values('9311028','CAMARAS DE COMERCIO');
insert into actividadbanxico values('9311036','CAMARAS INDUSTRIALES');
insert into actividadbanxico values('9311044','SOCIEDADES COOPERATIVAS');
insert into actividadbanxico values('9312018','ORGANIZACIONES DE ABOGADOS MEDICOS INGENIEROS Y OT');
insert into actividadbanxico values('9319014','ORGANIZACIONES CIVICAS');
insert into actividadbanxico values('9321019','ORGANIZACIONES LABORALES Y SINDICALES');
insert into actividadbanxico values('9322017','ORGANIZACIONES POLITICAS');
insert into actividadbanxico values('9331018','ORGANIZACIONES RELIGIOSAS');
insert into actividadbanxico values('9411018','GOBIERNO FEDERAL');
insert into actividadbanxico values('9411026','GOBIERNO ESTATAL');
insert into actividadbanxico values('9411034','GOBIERNO MUNICIPAL');
insert into actividadbanxico values('9411042','DEPARTAMENTO DEL DISTRITO FEDERAL');
insert into actividadbanxico values('9411886','USUARIOS MENORES DE GOBIERNO FEDERAL');
insert into actividadbanxico values('9411894','CARTERA DE GOBIERNO FEDERAL DE ESTADOS ANALITICOS');
insert into actividadbanxico values('9411901','USUARIOS MENORES DE GOBIERNO ESTATAL Y MUNICIPAL');
insert into actividadbanxico values('9411919','CARTERA DE GOBIERNO ESTATAL Y MUNICIPAL DE ESTADOS');
insert into actividadbanxico values('9411998','EMPLEADO PUBLICO');
insert into actividadbanxico values('9471012','PRESTACION DE SERVICIOS PUBLICOS Y SOCIALES');
insert into actividadbanxico values('9911018','INSTITUCIONES FINANCIERAS DEL EXTRANJERO');
insert into actividadbanxico values('9912016','CONSULADO');
insert into actividadbanxico values('9912024','GOBIERNO EXTRANJERO');
insert into actividadbanxico values('9919012','SERVICIOS DE OFICINAS Y REPRESENTACIONES DE OTROS');
insert into actividadbanxico values('9999999','NO CLASIFICADA');