drop table operacionesrelevantes;
CREATE TABLE operacionesrelevantes
(
	operacionesrelevantesid serial NOT NULL,
	autorizado integer,
	tiporeporte text,
	periodoreporte text,
	folio text,
	organismosupervisor text,
	claveentidad text,
	localidad text,
	sucursal text,
	tipooperacion text,
	intrumentomonetario text,
	numerocuenta text,
	monto text,
	moneda text,
	fechaoperacion text,
	fechadetencion text,
	nacionalidad text,
	tipopersona text,
	razonsocial text,
	nombre text,
	paterno text,
	materno text,
	RFC text,
	CURP text,
	fechanacimiento text,
	domicilio text,
	colonia text,
	ciudad text,
	telefono text,
	actividadeconomica text,
	nombreagente text,
	paternoagente text,
	maternoagente text,
	rfcagente text,
	curpagente text,
	consecutivocuentas text,
	numcuenta text,
	claveentidadfinanciera text,
	nombrecuentarelacionada text,
	paternocuentarelacionada text,
	maternocuentarelacionada text,
	descripcion text,
	razon text,
	ejercicio integer,
	periodo integer,
	CONSTRAINT operacionesrelevantes_pkey PRIMARY KEY (operacionesrelevantesid)
);