--paises
DROP table paisespld;
CREATE TABLE paisespld
(
  paisid serial NOT NULL,
  paisidpld numeric,
  clavepais text,
  paisnombre text,
  nocooperante integer,
  paraisofiscal integer,
  CONSTRAINT paisespld_pkey PRIMARY KEY (paisid)
);
--insertar paises
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(0,'ND','SE DESCONOCE',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(3,'AD','ANDORRA',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(4,'AE','EMIRATOS ARABES UNIDOS',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(5,'AF','AFGANISTAN',1,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(6,'AG','ANTIGUA Y BARBUDA',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(7,'AI','ANGUILA',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(8,'AL','ALBANIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(9,'AM','ARMENIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(10,'AN','ANTILLAS NEERLANDESAS',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(11,'AO','ANGOLA',1,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(12,'AQ','ANTARTIDA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(13,'AR','ARGENTINA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(14,'AS','SAMOA AMERICANA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(15,'AT','AUSTRIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(16,'AU','AUSTRALIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(17,'AW','ARUBA',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(18,'AX','ISLAS ÅLAND',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(19,'AZ','AZERBAIYAN',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(20,'BA','BOSNIA Y HERZEGOVINA',1,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(21,'BB','BARBADOS',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(22,'BD','BANGLADESH',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(23,'BE','BELGICA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(24,'BF','BURKINA FASO',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(25,'BG','BULGARIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(26,'BH','BAHREIN',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(27,'BI','BURUNDI',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(28,'BJ','BENIN',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(29,'BM','BERMUDAS',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(30,'BN','BRUNEI',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(31,'BO','BOLIVIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(32,'BR','BRASIL',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(33,'BS','BAHAMAS',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(34,'BT','BHUTAN',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(35,'BV','ISLA BOUVET',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(36,'BW','BOTSUANA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(37,'BY','BELARUS',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(38,'BZ','BELICE',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(39,'CA','CANADA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(40,'CC','ISLAS COCOS',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(41,'CD','REPUBLICA DEMOCRATICA DEL CONGO',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(42,'CF','REPUBLICA CENTROAFRICANA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(43,'CG','CONGO',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(44,'CH','SUIZA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(45,'CI','COSTA DE MARFIL',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(46,'CK','ISLAS COOK',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(47,'CL','CHILE',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(48,'CM','CAMERUN',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(49,'CN','CHINA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(50,'CO','COLOMBIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(51,'CP','CLIPPERTON',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(52,'CR','COSTA RICA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(53,'CU','CUBA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(54,'CV','CABO VERDE',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(55,'CX','ISLA CHRISTMAS',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(56,'CY','CHIPRE',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(57,'CZ','CHEQUIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(58,'DE','ALEMANIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(59,'DJ','YIBUTI',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(60,'DK','DINAMARCA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(61,'DM','DOMINICA',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(62,'DO','REPUBLICA DOMINICANA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(63,'DZ','ARGELIA',1,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(64,'EC','ECUADOR',1,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(65,'EE','ESTONIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(66,'EG','EGIPTO',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(67,'EH','SAHARA OCCIDENTAL',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(68,'EL','GRECIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(69,'ER','ERITREA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(70,'ES','ESPAÑA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(71,'ET','ETIOPIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(72,'FI','FINLANDIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(73,'FJ','FIYI',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(74,'FK','ISLAS MALVINAS',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(75,'FM','MICRONESIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(76,'FO','ISLAS FEROE',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(77,'FR','FRANCIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(78,'GA','GABON',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(79,'GD','GRANADA',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(80,'GE','GEORGIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(81,'GF','GUAYANA FRANCESA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(82,'GG','GUERNESEY',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(83,'GH','GHANA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(84,'GI','GIBRALTAR',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(85,'GL','GROENLANDIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(86,'GM','GAMBIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(87,'GN','GUINEA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(88,'GP','GUADALUPE',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(89,'GQ','GUINEA ECUATORIAL',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(90,'GS','GEORGIA DEL SUR E ISLAS SANDWICH DEL SUR',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(91,'GT','GUATEMALA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(92,'GU','GUAM',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(93,'GW','GUINEA-BISSAU',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(94,'GY','GUYANA',1,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(95,'HK','HONG KONG',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(96,'HM','ISLAS HEARD Y MCDONALD',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(97,'HN','HONDURAS',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(98,'HR','CROACIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(99,'HT','HAITI',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(100,'HU','HUNGRIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(101,'ID','INDONESIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(102,'IE','IRLANDA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(103,'IL','ISRAEL',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(104,'IM','ISLA DE MAN',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(105,'IN','INDIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(106,'IO','TERRITORIO BRITANICO DEL OCEANO INDICO',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(107,'IQ','IRAQ',1,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(108,'IR','IRAN',1,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(109,'IS','ISLANDIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(110,'IT','ITALIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(111,'JE','JERSEY',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(112,'JM','JAMAICA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(113,'JO','JORDANIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(114,'JP','JAPON',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(115,'KE','KENIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(116,'KG','KIRGUISTAN',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(117,'KH','CAMBOYA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(118,'KI','KIRIBATI',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(119,'KM','COMORAS',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(120,'KN','SAN CRISTOBAL Y NIEVES',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(121,'KP','COREA DEL NORTE',1,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(122,'KR','COREA DEL SUR',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(123,'KW','KUWAIT',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(124,'KY','ISLAS CAIMAN',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(125,'KZ','KAZAJSTAN',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(126,'LA','LAOS',1,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(127,'LB','LIBANO',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(128,'LC','SANTA LUCIA',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(129,'LI','LIECHTENSTEIN',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(130,'LK','SRI LANKA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(131,'LR','LIBERIA',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(132,'LS','LESOTHO',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(133,'LT','LITUANIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(134,'LU','LUXEMBURGO',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(135,'LV','LETONIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(136,'LY','LIBIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(137,'MA','MARRUECOS',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(138,'MC','MONACO',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(139,'MD','MOLDOVA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(140,'ME','MONTENEGRO',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(141,'MG','MADAGASCAR',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(142,'MH','ISLAS MARSHALL',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(143,'ML','MALI',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(144,'MM','MYANMAR',1,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(145,'MN','MONGOLIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(146,'MO','MACAO',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(147,'MP','ISLAS MARIANAS DEL NORTE',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(148,'MQ','MARTINICA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(149,'MR','MAURITANIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(150,'MS','MONTSERRAT',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(151,'MT','MALTA',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(152,'MU','MAURICIO',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(153,'MV','MALDIVAS',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(154,'MW','MALAWI',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(155,'MX','MEXICO',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(156,'MY','MALASIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(157,'MZ','MOZAMBIQUE',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(158,'NA','NAMIBIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(159,'NC','NUEVA CALEDONIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(160,'NE','NIGER',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(161,'NF','ISLA NORFOLK',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(162,'NG','NIGERIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(163,'NI','NICARAGUA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(164,'NL','PAISES BAJOS',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(165,'NO','NORUEGA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(166,'NP','NEPAL',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(167,'NR','NAURU',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(168,'NU','NIUE',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(169,'NZ','NUEVA ZELANDA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(170,'OM','OMAN',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(171,'PA','PANAMA',1,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(172,'PE','PERU',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(173,'PF','POLINESIA FRANCESA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(174,'PG','PAPUA NUEVA GUINEA',1,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(175,'PH','FILIPINAS',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(176,'PK','PAKISTAN',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(177,'PL','POLONIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(178,'PM','SAN PEDRO Y MIQUELON',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(179,'PN','ISLAS PITCAIRN',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(180,'PR','PUERTO RICO',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(181,'PS','TERRITORIOS PALESTINOS',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(182,'PT','PORTUGAL',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(183,'PW','PALAOS',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(184,'PY','PARAGUAY',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(185,'QA','QATAR',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(186,'RE','REUNION',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(187,'RO','RUMANIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(188,'RS','SERBIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(189,'RU','RUSIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(190,'RW','RUANDA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(191,'SA','ARABIA SAUDI',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(192,'SB','ISLAS SALOMON',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(193,'SC','SEYCHELLES',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(194,'SD','SUDAN',1,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(195,'SE','SUECIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(196,'SG','SINGAPUR',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(197,'SH','SANTA ELENA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(198,'SI','ESLOVENIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(199,'SJ','SVALBARD Y JAN MAYEN',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(200,'SK','ESLOVAQUIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(201,'SL','SIERRA LEONA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(202,'SM','SAN MARINO',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(203,'SN','SENEGAL',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(204,'SO','SOMALIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(205,'SR','SURINAM',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(206,'ST','SANTO TOME Y PRINCIPE',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(207,'SV','EL SALVADOR',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(208,'SY','SIRIA',1,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(209,'SZ','SUAZILANDIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(210,'TC','ISLAS TURCAS Y CAICOS',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(211,'TD','CHAD',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(212,'TF','TERRITORIOS AUSTRALES FRANCESES',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(213,'TG','TOGO',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(214,'TH','TAILANDIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(215,'TJ','TAYIKISTAN',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(216,'TK','TOKELAU',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(217,'TL','TIMOR ORIENTAL',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(218,'TM','TURKMENISTAN',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(219,'TN','TUNEZ',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(220,'TO','TONGA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(221,'TR','TURQUIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(222,'TT','TRINIDAD Y TOBAGO',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(223,'TV','TUVALU',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(224,'TW','TAIWAN',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(225,'TZ','TANZANIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(226,'UA','UCRANIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(227,'UG','UGANDA',1,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(228,'UK','REINO UNIDO',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(229,'UM','ISLAS MENORES ALEJADAS DE LOS ESTADOS UNIDOS',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(230,'US','ESTADOS UNIDOS',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(231,'UY','URUGUAY',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(232,'UZ','UZBEKISTAN',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(233,'VA','SANTA SEDE / ESTADO DE LA CIUDAD DEL VATICANO',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(234,'VC','SAN VICENTE Y LAS GRANADINAS',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(235,'VE','VENEZUELA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(236,'VG','ISLAS VIRGENES BRITANICAS',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(237,'VI','ISLAS VIRGENES DE LOS ESTADOS UNIDOS',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(238,'VN','VIETNAM',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(239,'VU','VANUATU',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(240,'WF','WALLIS Y FUTUNA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(241,'WS','SAMOA',0,1);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(242,'YE','YEMEN',1,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(243,'YT','MAYOTTE',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(244,'ZA','SUDAFRICA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(245,'ZM','ZAMBIA',0,0);
insert into paisespld(paisidpld,clavepais,paisnombre,nocooperante,paraisofiscal)values(246,'ZW','ZIMBABUE',0,0);