create table remesa
(
	remesaid serial not null,
	socioid integer references socio(socioid),     
	sujetoid integer references sujeto(sujetoid), 
	tipoidentificacion character varying(20), 
	numidentificacion character varying(15), 
	paisnacimiento character varying(50), 
	fechanacimiento date,
	nacionalidad character varying(50), 
	estadonacimiento character varying(50), 
	genero character varying(10), 
	rfc character varying(16), 
	paisrfc character varying(50), 
	curp character varying(20), 
	profesion character varying(200), 
	actividad character varying(200), 
	email character varying(50), 
	fiel character varying(100), 
	tiporemesa character varying(30), 
	remesadora character varying(80),
	monto_pesos numeric, 
	monto_dolares numeric, 
	fecha date,    
	folioenvrec integer,
	procedenciaenvio character varying(100),
	beneficiario character varying(100),
	recibe_envia integer,
	tipopersona integer,
	razonsocial character varying(200),
	fechaconstitucion date,
	domicilioid integer references domicilio (domicilioid),
	primary key (remesaid)
);