\i	mod_garantiaprendaria.sql
\i	mod_garantiahipotecaria.sql
\i	mod_solicitudprestamo.sql
\i	spisolicitudprestamo_v2.sql
\i	spusolicitudprestamo_v2.sql
\i	spssolitudesprestamo.sql
\i	ingresosactividad.sql
\i	ingresosterceros.sql
\i	ingresostrabajo.sql
\i	ingresosinvestigacion.sql
\i	ingresossolicitud.sql
\i	spiingresostrabajo.sql
\i	spiingresosactividad.sql
\i	spiingresosterceros.sql
\i	spugarantiaprendaria.sql
\i	spigarantiaprendaria.sql
\i	spugarantiahipotecaria.sql
\i	spigarantiahipotecaria.sql
\i	update_desctipoprestamo.sql
\i	ultimafechaburo.sql
\i	condicionescredito.sql
\i	datoscondicionescredito.sql
\i	catalogofinalidad.sql
\i	tipocreditofinalidad.sql
\i	analisiscredito.sql
\i	spssolsociosioef.sql
\i	depinvestigacion.sql
\i	propiedadinvestigacredito.sql
\i	gralesinvestigacion.sql
\i	spigeneralesinvestigacion.sql
\i	infoviviendainvesigacredito.sql
\i	spiviviendainvestigacion.sql
\i	mod_amortizaciones.sql
\i	mod_prestamos.sql
\i	permisos.sql
\i	spiprestamos_v3.sql
\i	spsamortizaciones.sql
\i	spsprestamos.sql
\i	ultimaconsultaburo.sql
\i tablasCreditos.sql
\i spimovicaja_Ver011.sql
\i columna_garprendaria.sql
\i liquidaconrenovado.sql
\i spsinversiongarantia.sql
\i spsinversiongrabada.sql
\i garantiainversion.sql
\i rangoautorizacion.sql
\i insertrangoautorizacion.sql
\i tablarenovado.sql
\i tablarestructurado.sql
\i garantiadicional.sql
\i guardavalores.sql
\i instrumentacion.sql
\i base_de_imagenes.sql
\i datos_base_imagenes.sql