insert into catalogodocumentos (descripcion) values ('IDENTIFICACION (IFE/INE)','',0,'',0,0,0,0,true,true);
insert into catalogodocumentos (descripcion) values ('IDENTIFICACION (PASAPORTE)');
insert into catalogodocumentos (descripcion) values ('IDENTIFICACION (CEDULA PROFESIONAL)');
insert into catalogodocumentos (descripcion) values ('IDENTIFICACION (CARTILLA MILITAR)');
insert into catalogodocumentos (descripcion) values ('ACTA DE NACIMIENTO');
insert into catalogodocumentos (descripcion) values ('CURP');
insert into catalogodocumentos (descripcion) values ('COMP. DE DOM. (RECIBO LUZ)');
insert into catalogodocumentos (descripcion) values ('COMP. DE DOM. (RECIBO TELEFONO)');
insert into catalogodocumentos (descripcion) values ('COMP. DE DOM. (PAGO PREDIAL)');
insert into catalogodocumentos (descripcion) values ('COMP. DE DOM. (CARTA DE ORIGEN Y VENCIDAD)');
insert into catalogodocumentos (descripcion) values ('COMP. DE DOM. (OTRO)');
insert into catalogodocumentos (descripcion) values ('SOLICITUD DE INGRESO');
insert into catalogodocumentos (descripcion) values ('CONTRATO DE DEPOSITO DE DINERO');
insert into catalogodocumentos (descripcion) values ('CARATULA DEL CONTRATO DE DEPOSITOS A LA VISTA');
insert into catalogodocumentos (descripcion) values ('ASIGNACION DE BENEFICIARIO');
insert into catalogodocumentos (descripcion) values ('AVISO DE PRIVACIDAD');
insert into catalogodocumentos (descripcion) values ('CARTA DE RESTRICCION AL AHORRO Y PRESTAMO');
insert into catalogodocumentos (descripcion) values ('SOLICITUD DE CREDITO');
insert into catalogodocumentos (descripcion) values ('COMPROBANTE DE INGRESOS');
insert into catalogodocumentos (descripcion) values ('AUTORIZACION DE CONSULTA DE BURO DE CREDITO');
insert into catalogodocumentos (descripcion) values ('GARANTIA PREND. (CONTRATO DE COMPRA VENTA)');
insert into catalogodocumentos (descripcion) values ('GARANTIA PREND. (ACTA DE POSESION)');
insert into catalogodocumentos (descripcion) values ('GARANTIA PREND. (FACTURA DE BIEN)');
insert into catalogodocumentos (descripcion) values ('GARANTIA PREND. (OTRO)');
insert into catalogodocumentos (descripcion) values ('GARANTIA HIP. (AVALUO DE LA PROPIEDAD)');
insert into catalogodocumentos (descripcion) values ('GARANTIA HIP. (LIBERTAD DE GRAVAMEN)');
insert into catalogodocumentos (descripcion) values ('REPORTE DE INVESTIGACION DE CREDITO');
insert into catalogodocumentos (descripcion) values ('CROQUIS DE LOCALIZACION');
insert into catalogodocumentos (descripcion) values ('FOTOGRAFIA DE DOMICILIO FACHADA');
insert into catalogodocumentos (descripcion) values ('FOTOGRAFIA DE DOMICILIO INTERIOR');
insert into catalogodocumentos (descripcion) values ('FOTOGRAFIA DE NEGOCIO FACHADA');
insert into catalogodocumentos (descripcion) values ('FOTOGRAFIA DE NEGOCIO INTERIOR');
insert into catalogodocumentos (descripcion) values ('BURO DE CREDITO');
insert into catalogodocumentos (descripcion) values ('REPORTE DE ANALISIS DE CREDITO');
insert into catalogodocumentos (descripcion) values ('CONTRATO DE APERTURA DE CREDITO');
insert into catalogodocumentos (descripcion) values ('PAGARE');
insert into catalogodocumentos (descripcion) values ('PLAN DE PAGOS');
insert into catalogodocumentos (descripcion) values ('CONTRATO DE DISPOSICION DE HABERES');
insert into catalogodocumentos (descripcion) values ('GARANTIA HIP. (DICTAMEN LEGAL)');
insert into catalogodocumentos (descripcion) values ('GARANTIA HIP. (CONTRATO HIPOTECARIO)');
insert into catalogodocumentos (descripcion) values ('GARANTIA HIP. (REGISTRO DE HIPOTECA)');
insert into catalogodocumentos (descripcion) values ('OTRO');

insert into proceso (descripcion) values('INGRESO DE SOCIO');
insert into proceso (descripcion) values('INSTRUMENTACION DE INGRESO DE SOCIO');
insert into proceso (descripcion) values('SOLICITUD DE CREDITO');
insert into proceso (descripcion) values('SOLICITUD DE CREDITO AVAL');
insert into proceso (descripcion) values('INVESTIGACION DE CREDITO');
insert into proceso (descripcion) values('INVESTIGACION DE CREDITO AVAL');
insert into proceso (descripcion) values('ANALISIS DE CREDITO');
insert into proceso (descripcion) values('INSTRUMENTACION DE CREDITO');

insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (1,1,'S',1);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (1,2,'N',1);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (1,3,'N',1);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (1,4,'N',1);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (1,5,'S',2);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (1,6,'S',3);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (1,7,'S',4);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (1,8,'N',4);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (1,9,'N',4);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (1,10,'N',4);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (1,11,'N',4);

insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (2,12,'S',5);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (2,13,'S',6);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (2,14,'S',7);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (2,15,'S',8);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (2,16,'S',9);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (2,17,'S',10);

insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (3,18,'S',11);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (3,19,'S',12);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (3,20,'S',13);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (3,21,'S',14);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (3,22,'N',14);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (3,23,'N',14);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (3,24,'N',14);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (3,25,'S',15);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (3,26,'S',16);

insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (4,1,'S',17);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (4,2,'N',17);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (4,3,'N',17);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (4,4,'N',17);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (4,5,'S',18);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (4,6,'S',19);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (4,7,'S',20);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (4,8,'N',20);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (4,9,'N',20);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (4,10,'N',20);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (4,11,'N',20);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (4,19,'S',21);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (4,20,'S',22);

insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (5,27,'S',23);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (5,28,'S',24);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (5,29,'S',25);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (5,29,'S',26);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (5,30,'S',27);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (5,30,'S',28);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (5,31,'S',29);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (5,31,'S',30);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (5,32,'S',31);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (5,32,'S',32);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (5,33,'S',33);

insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (6,27,'S',24);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (6,28,'S',25);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (6,29,'S',26);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (6,29,'S',27);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (6,30,'S',28);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (6,30,'S',29);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (6,31,'S',30);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (6,31,'S',31);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (6,32,'S',32);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (6,32,'S',33);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (6,33,'S',34);

insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (7,34,'S',35);

insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (8,35,'S',36);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (8,36,'S',37);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (8,37,'S',38);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (8,38,'S',39);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (8,39,'S',40);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (8,40,'S',41);
insert into documentorequerido (procesoid,documentoid,requerido,grupo) values (8,41,'S',42);
