CREATE TABLE viviendainvestigacion
(
  viviendaid serial not null,
  solicitudprestamoid integer  REFERENCES solicitudprestamo(solicitudprestamoid),
  sujetoid integer REFERENCES sujeto(sujetoid),
  aguapotable integer,
  electricidad integer,
  telefono integer,
  drenaje integer,
  tvcable integer,
  intenet integer,
  tipovivienda  integer,
  familia integer,
  amigos integer,
  parientes integer,
  otros integer,
  numpersonas integer,
  sala integer,
  cocina integer,
  comedor integer,
  cochera integer,
  bano     integer,
  numrecamaras integer,
  tipoparedes integer,
  tipopiso integer,
  tipotecho integer,
  estereo integer,
  estufa integer,
  computadora integer,
  televisor integer,
  lavadora integer,
  refrigerador integer,
  tipopropiedad integer,
  clavecatrastal character varying(20),
  inscripcion character varying(50),
  fechainscripcion date,
  observaciones text
  )
WITH (
  OIDS=FALSE
);
