CREATE TABLE tiporenovado
(
 tiporenovadoid             	character(3)   not null,
 cuentaactivo                   character(24)  not null,
 cuentaactivovencida            character(24)  not null,
 cuentaintnormal                character(24)  not null,
 cuentaintnormalvencida         character(24)  not null,
 cuentaintnormalnocob           character(24)  not null,
 cuentaintmora                  character(24)  not null,
 cuentaintmoravencida           character(24)  not null,
 cuentaiva                      character(24)  not null,
 cuentariesgocred               character(24)  not null,
 cuentaordeninteres             character(24)  not null,
 cuentaordenaval                character(24)  not null,
 tipomovimientoid               character(2)   REFERENCES tipomovimiento(tipomovimientoid) not null,
 desctipoprestamo               character(30),  
 tantos                         integer        not null,
 tasa_normal                    numeric        not null,
 tasa_mora                      numeric        not null,
 aplicaivaprestamo              character(1)   not null,
 diastraspasoavencida           integer        not null,
 cuentaintdevnocobres           character(24)  not null,
 cuentariesgocredres            character(24)  not null,
 cuentaintmoranocobact          character(24)  not null,
 cuentaintmoradevnocobres       character(24)  not null,
 ordendeudornormalbonificado    character(24),  
 ordenacredornormalbonificado   character(24), 
 cuentafondorecuperacion        character(24), 
 cuentagtosadm                  character(24),  
 cuentaintnormalresvencida      character(24),  
 ordeninteresacreedor           character(24),  
 calculonormalid                integer     REFERENCES calculo(calculoid)    not null,
 calculomoraid                  integer     REFERENCES calculo(calculoid)   not null,
 clavefinalidad                 character(3) REFERENCES finalidades(clavefinalidad)  not null,
 cuentaintnormalresvigente      character(24),  
 cuentaordenavalacredor         character(24),  
 cuentagarantiadeudor           character(24),  
 cuentagarantiaacredor          character(24),  
 cuentaprovisioniva             character(24),  
 montomaximo                    numeric,        
 plazomaximo                    integer,        
 montominimo                    numeric,        
 avalesminimos                  integer,        
 periododiasdefault             integer,        
 estatus                        integer,        
 comision                       numeric,        
 ivacomision                    numeric,        
 cuentacomision                 character(24),  
 cuentaivacomision              character(24),  
 nivelautorizacion              integer,        
 reciprocidad                   numeric,       
 prestamogrupal                 integer        default 0,
 clasificacioncontable          character(24),  
 tipoprestamores                character(3),   
 moravigentebalance             character(24),  
 moravencidobalance             character(24),  
 moravigenteresultado           character(24),  
 moravencidoresultado           character(24),  
 moractaordendeudora            character(24),  
 moractaordenacredora           character(24),  
PRIMARY KEY (tiporenovadoid)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE tiporenovado
  OWNER TO postgres;
  

