drop table tipocreditofinalidad;
CREATE TABLE tipocreditofinalidad
(
	tipoprestamoid character(3) references tipoprestamo(tipoprestamoid),
	finalidadid integer references catalogofinalidad(finalidadid),
	UNIQUE (tipoprestamoid,finalidadid) 
);
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (1,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (2,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (3,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (4,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (5,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (6,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (7,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (8,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (9,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (10,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (11,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (12,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (13,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (14,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (15,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (16,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (17,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (18,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (19,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (20,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (21,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (22,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (23,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (24,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (25,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (26,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (27,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (28,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (29,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (30,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (31,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (32,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (33,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (34,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (35,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (36,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (37,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (38,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (39,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (40,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (41,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (42,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (43,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (44,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (45,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (46,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (47,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (48,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (49,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (50,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (51,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (52,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (53,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (54,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (55,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (56,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (57,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (58,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (59,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (60,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (61,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (62,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (63,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (64,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (65,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (66,'N1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (67,'N1');

insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (1,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (2,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (3,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (4,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (5,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (6,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (7,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (8,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (9,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (10,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (11,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (12,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (13,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (14,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (15,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (16,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (17,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (18,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (19,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (20,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (21,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (22,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (23,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (24,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (25,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (26,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (27,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (28,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (29,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (30,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (31,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (32,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (33,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (34,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (35,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (36,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (37,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (38,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (39,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (40,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (41,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (42,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (43,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (44,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (45,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (46,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (47,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (48,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (49,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (50,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (51,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (52,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (53,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (54,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (55,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (56,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (57,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (58,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (59,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (60,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (61,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (62,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (63,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (64,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (65,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (66,'N4');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (67,'N4');

insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (7,'N5');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (9,'N5');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (10,'N5');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (11,'N5');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (12,'N5');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (13,'N5');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (14,'N5');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (15,'N5');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (16,'N5');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (31,'N5');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (32,'N5');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (33,'N5');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (34,'N5');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (35,'N5');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (60,'N5');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (61,'N5');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (62,'N5');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (63,'N5');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (64,'N5');

insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (48,'N13');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (49,'N13');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (50,'N13');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (59,'N13');

insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (41,'N14');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (42,'N14');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (43,'N14');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (44,'N14');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (59,'N14');

insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (1,'N15');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (2,'N15');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (3,'N15');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (4,'N15');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (5,'N15');

insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (17,'N20');

insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (1,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (2,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (3,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (4,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (5,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (6,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (7,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (8,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (9,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (10,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (11,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (12,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (13,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (14,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (15,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (16,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (17,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (18,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (19,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (20,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (21,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (22,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (23,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (24,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (25,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (26,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (27,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (28,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (29,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (30,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (31,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (32,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (33,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (34,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (35,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (36,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (37,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (38,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (39,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (40,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (41,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (42,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (43,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (44,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (45,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (46,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (47,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (48,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (49,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (50,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (51,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (52,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (53,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (54,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (55,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (56,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (57,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (58,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (59,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (60,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (61,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (62,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (63,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (64,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (65,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (66,'N7');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (67,'N7');

insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (1,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (2,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (3,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (4,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (5,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (6,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (7,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (8,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (9,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (10,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (11,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (12,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (13,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (14,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (15,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (16,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (17,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (18,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (19,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (20,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (21,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (22,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (23,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (24,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (25,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (26,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (27,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (28,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (29,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (30,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (31,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (32,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (33,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (34,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (35,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (36,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (37,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (38,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (39,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (40,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (41,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (42,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (43,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (44,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (45,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (46,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (47,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (48,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (49,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (50,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (51,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (52,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (53,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (54,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (55,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (56,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (57,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (58,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (59,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (60,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (61,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (62,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (63,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (64,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (65,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (66,'N16');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (67,'N16');

insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (1,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (2,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (3,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (4,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (5,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (6,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (7,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (8,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (9,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (10,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (11,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (12,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (13,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (14,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (15,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (16,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (17,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (18,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (19,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (20,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (21,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (22,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (23,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (24,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (25,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (26,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (27,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (28,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (29,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (30,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (31,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (32,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (33,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (34,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (35,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (36,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (37,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (38,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (39,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (40,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (41,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (42,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (43,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (44,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (45,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (46,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (47,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (48,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (49,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (50,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (51,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (52,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (53,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (54,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (55,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (56,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (57,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (58,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (59,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (60,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (61,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (62,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (63,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (64,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (65,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (66,'N8');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (67,'N8');

insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (6,'N9');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (7,'N9');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (8,'N9');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (9,'N9');

insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (51,'P1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (52,'P1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (53,'P1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (54,'P1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (55,'P1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (56,'P1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (57,'P1');
insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (58,'P1');

insert into tipocreditofinalidad (finalidadid,tipoprestamoid) values (71,'P4');

insert into tipocreditofinalidad values ('N54',68);
insert into tipocreditofinalidad values ('N16',68);
insert into tipocreditofinalidad values ('N8' ,68);
insert into tipocreditofinalidad values ('N53',68);
insert into tipocreditofinalidad values ('N1',68);
insert into tipocreditofinalidad values ('N13',68);
insert into tipocreditofinalidad values ('P4',68); 
insert into tipocreditofinalidad values ('N15',68);
insert into tipocreditofinalidad values ('N9',68); 
insert into tipocreditofinalidad values ('N21',68);
insert into tipocreditofinalidad values ('N5',68); 
insert into tipocreditofinalidad values ('N4',68); 
insert into tipocreditofinalidad values ('P1',68); 
insert into tipocreditofinalidad values ('CF',68); 
insert into tipocreditofinalidad values ('N14',68);
insert into tipocreditofinalidad values ('N22',68);
insert into tipocreditofinalidad values ('N7',68); 


insert into tipocreditofinalidad values ('N54',69);
insert into tipocreditofinalidad values ('N16',69);
insert into tipocreditofinalidad values ('N8' ,69);
insert into tipocreditofinalidad values ('N53',69);
insert into tipocreditofinalidad values ('N1',69);
insert into tipocreditofinalidad values ('N13',69);
insert into tipocreditofinalidad values ('P4',69); 
insert into tipocreditofinalidad values ('N15',69);
insert into tipocreditofinalidad values ('N9',69); 
insert into tipocreditofinalidad values ('N21',69);
insert into tipocreditofinalidad values ('N5',69); 
insert into tipocreditofinalidad values ('N4',69); 
insert into tipocreditofinalidad values ('P1',69); 
insert into tipocreditofinalidad values ('CF',69); 
insert into tipocreditofinalidad values ('N14',69);
insert into tipocreditofinalidad values ('N22',69);
insert into tipocreditofinalidad values ('N7',69);

insert into tipocreditofinalidad values ('N54',70);
insert into tipocreditofinalidad values ('N16',70);
insert into tipocreditofinalidad values ('N8' ,70);
insert into tipocreditofinalidad values ('N53',70);
insert into tipocreditofinalidad values ('N1',70);
insert into tipocreditofinalidad values ('N13',70);
insert into tipocreditofinalidad values ('P4',70); 
insert into tipocreditofinalidad values ('N15',70);
insert into tipocreditofinalidad values ('N9',70); 
insert into tipocreditofinalidad values ('N21',70);
insert into tipocreditofinalidad values ('N5',70); 
insert into tipocreditofinalidad values ('N4',70); 
insert into tipocreditofinalidad values ('P1',70); 
insert into tipocreditofinalidad values ('CF',70); 
insert into tipocreditofinalidad values ('N14',70);
insert into tipocreditofinalidad values ('N22',70);
insert into tipocreditofinalidad values ('N7',70);