update tipoprestamo set desctipoprestamo='CREDIMATICO AHORRO' where tipoprestamoid='N8 ';
update tipoprestamo set desctipoprestamo='CREDIEMPLEADO' where tipoprestamoid='N7 ';
update tipoprestamo set desctipoprestamo='CREDIUNION CICLO 3' where tipoprestamoid='N53';
update tipoprestamo set desctipoprestamo='CREDIUNION CICLO 4' where tipoprestamoid='N54';
update tipoprestamo set desctipoprestamo='CREDIUNION' where tipoprestamoid='N5 ';
update tipoprestamo set desctipoprestamo='CREDICUMPLIDO' where tipoprestamoid='N4 ';
update tipoprestamo set desctipoprestamo='CREDI CAMPO' where tipoprestamoid='P1 ';
update tipoprestamo set desctipoprestamo='AUTOESTRENA' where tipoprestamoid='N9 ';
update tipoprestamo set desctipoprestamo='CREDISOLUCION' where tipoprestamoid='N1 ';
update tipoprestamo set estatus=0 where tipoprestamoid in ('CAS','R2','C9','T2','C1','C4');