update estadosmex set abre_estado='AGS' where nombreestadomex = 'AGUASCALIENTES' and claveestadomex='01';
update estadosmex set abre_estado='BCN' where nombreestadomex = 'BAJA CALIFORNIA' and claveestadomex='02';
update estadosmex set abre_estado='BCS' where nombreestadomex = 'BAJA CALIFORNIA SUR' and claveestadomex='03';
update estadosmex set abre_estado='CAM' where nombreestadomex = 'CAMPECHE' and claveestadomex='04';
update estadosmex set abre_estado='COA' where nombreestadomex = 'COAHUILA DE ZARAGOZA' and claveestadomex='05';
update estadosmex set abre_estado='COL' where nombreestadomex = 'COLIMA' and claveestadomex='06';
update estadosmex set abre_estado='CHS' where nombreestadomex = 'CHIAPAS' and claveestadomex='07';
update estadosmex set abre_estado='CHI' where nombreestadomex = 'CHIHUAHUA' and claveestadomex='08';
update estadosmex set abre_estado='DF' where nombreestadomex = 'DISTRITO FEDERAL' and claveestadomex='09';
update estadosmex set abre_estado='DGO' where nombreestadomex = 'DURANGO' and claveestadomex='10';
update estadosmex set abre_estado='GTO' where nombreestadomex = 'GUANAJUATO' and claveestadomex='11';
update estadosmex set abre_estado='GRO' where nombreestadomex = 'GUERRERO' and claveestadomex='12';
update estadosmex set abre_estado='HGO' where nombreestadomex = 'HIDALGO' and claveestadomex='13';
update estadosmex set abre_estado='JAL' where nombreestadomex = 'JALISCO' and claveestadomex='14';
update estadosmex set abre_estado='EM' where nombreestadomex = 'MÉXICO' and claveestadomex='15';
update estadosmex set abre_estado='MICH' where nombreestadomex = 'MICHOACÁN DE OCAMPO' and claveestadomex='16';
update estadosmex set abre_estado='MOR' where nombreestadomex = 'MORELOS' and claveestadomex='17';
update estadosmex set abre_estado='NAY' where nombreestadomex = 'NAYARIT' and claveestadomex='18';
update estadosmex set abre_estado='NL' where nombreestadomex = 'NUEVO LEÓN' and claveestadomex='19';
update estadosmex set abre_estado='OAX' where nombreestadomex = 'OAXACA' and claveestadomex='20';
update estadosmex set abre_estado='PUE' where nombreestadomex = 'PUEBLA' and claveestadomex='21';
update estadosmex set abre_estado='QRO' where nombreestadomex = 'QUERÉTARO DE ARTEAGA' and claveestadomex='22';
update estadosmex set abre_estado='QR' where nombreestadomex = 'QUINTANA ROO' and claveestadomex='23';
update estadosmex set abre_estado='SLP' where nombreestadomex = 'SAN LUÍS POTOSÍ' and claveestadomex='24';
update estadosmex set abre_estado='SIN' where nombreestadomex = 'SINALOA' and claveestadomex='25';
update estadosmex set abre_estado='SON' where nombreestadomex = 'SONORA' and claveestadomex='26';
update estadosmex set abre_estado='TAB' where nombreestadomex = 'TABASCO' and claveestadomex='27';
update estadosmex set abre_estado='TAM' where nombreestadomex = 'TAMAULIPAS' and claveestadomex='28';
update estadosmex set abre_estado='TLA' where nombreestadomex = 'TLAXCALA' and claveestadomex='29';
update estadosmex set abre_estado='VER' where nombreestadomex = 'VERACRUZ LLAVE' and claveestadomex='30';
update estadosmex set abre_estado='YUC' where nombreestadomex = 'YUCATÁN' and claveestadomex='31';
update estadosmex set abre_estado='ZAC' where nombreestadomex = 'ZACATECAS' and claveestadomex='32';