CREATE TABLE credito_amortizaciones_historico(
  amortizacionid serial NOT NULL,
  prestamoid int4 NOT NULL references prestamos(prestamoid),
  numamortizacion int4 NOT NULL,
  fechadepago date NOT NULL,
  importeamortizacion numeric NOT NULL,
  interesnormal numeric NOT NULL,
  saldo_absoluto numeric NOT NULL,
  interespagado numeric NOT NULL,
  abonopagado numeric NOT NULL,
  ultimoabono date NOT NULL,
  iva numeric,
  totalpago numeric,
  ahorro numeric DEFAULT 0,
  ahorropagado numeric DEFAULT 0,
  cobranza numeric DEFAULT 0,
  cobranzapagado numeric DEFAULT 0,
  moratoriopagado numeric,
  version integer,
  PRIMARY KEY (amortizacionid)
);